version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
  settings:
    staticcheck:
      checks:
        - all
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - text: 'Error return value of `.*(Close|Remove|RemoveAll|Fprint).*` is not checked'
        linters:
          - errcheck
