package kubernetesdeploy

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"syscall"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestRenderAndCheckGitOpsApplicationOnly(t *testing.T) {
	dir := writeGitOpsConsumer(t, "mode: cron\n", "", nil)
	opts := gitOpsTestOptions(dir)
	var output bytes.Buffer
	if err := RenderGitOps(opts, &output); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"README.md", "kustomization.yaml", "sources/kustomization.yaml", "sources/application-chart.yaml", "application/namespace.yaml", "application/values-configmap.yaml", "application/helmrelease.yaml", "application/kustomization.yaml"} {
		if _, err := os.Stat(filepath.Join(dir, "gitops", filepath.FromSlash(name))); err != nil {
			t.Errorf("missing %s: %v", name, err)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "gitops", "platform", "helmrelease.yaml")); !os.IsNotExist(err) {
		t.Fatalf("application-only render created platform HelmRelease: %v", err)
	}
	application := readGitOpsYAML(t, filepath.Join(dir, "gitops", "application", "helmrelease.yaml"))
	spec := application["spec"].(map[string]any)
	if _, ok := spec["dependsOn"]; ok {
		t.Fatal("application-only HelmRelease has dependsOn")
	}
	if spec["targetNamespace"] != "aster" || spec["timeout"] != "15m" {
		t.Fatalf("unexpected HelmRelease contract: %#v", spec)
	}
	if err := CheckGitOps(opts, &output); err != nil {
		t.Fatal(err)
	}
	readme, err := os.ReadFile(filepath.Join(dir, "gitops", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"generated by Aster", "ConfigMaps contain project", "no Secret values", "reverting and merging"} {
		if !bytes.Contains(readme, []byte(want)) {
			t.Errorf("README missing %q", want)
		}
	}
}

func TestRenderGitOpsFixEnabledIncludesPairedPlatform(t *testing.T) {
	app := "mode: cron\n" + gitOpsFixAppValues("aster-execution", "kata-vm-isolation", "fix-workload")
	platform := `application:
  releaseName: sample
execution:
  namespace: aster-execution
  runtimeClassName: kata-vm-isolation
  workloadServiceAccountName: fix-workload
`
	dir := writeGitOpsConsumer(t, app, platform, nil)
	opts := gitOpsTestOptions(dir)
	opts.ExecutionNamespace = "aster-execution"
	if err := RenderGitOps(opts, nil); err != nil {
		t.Fatal(err)
	}
	application := readGitOpsYAML(t, filepath.Join(dir, "gitops", "application", "helmrelease.yaml"))
	dependsOn := application["spec"].(map[string]any)["dependsOn"].([]any)
	if got := dependsOn[0].(map[string]any)["name"]; got != "sample-platform" {
		t.Fatalf("dependsOn = %v", got)
	}
	platformRelease := readGitOpsYAML(t, filepath.Join(dir, "gitops", "platform", "helmrelease.yaml"))
	platformSpec := platformRelease["spec"].(map[string]any)
	if platformSpec["releaseName"] != "sample-platform" || platformSpec["targetNamespace"] != "aster" {
		t.Fatalf("platform HelmRelease = %#v", platformSpec)
	}
	for _, sourcePath := range []string{"application-chart.yaml", "platform-chart.yaml"} {
		source := readGitOpsYAML(t, filepath.Join(dir, "gitops", "sources", sourcePath))
		if source["apiVersion"] != "source.toolkit.fluxcd.io/v1" || source["spec"].(map[string]any)["ref"].(map[string]any)["tag"] != "0.9.0" {
			t.Fatalf("invalid source %s: %#v", sourcePath, source)
		}
	}
	if err := CheckGitOps(opts, nil); err != nil {
		t.Fatal(err)
	}
}

func TestGitOpsValuesPreserveExactInputsAndSortedSkills(t *testing.T) {
	projectYAML := gitOpsProject + "categories:\n  - match: periodic\n    id: periodic\n    label: Periodic\n"
	prompt := "first line\n\n  indented line\nlast line\n"
	dir := t.TempDir()
	writeGitOpsFile(t, filepath.Join(dir, "project.yaml"), projectYAML)
	writeGitOpsFile(t, filepath.Join(dir, "prompts", "system.md"), prompt)
	writeGitOpsFile(t, filepath.Join(dir, "deploy", "values.yaml"), "mode: cron\nreplicaCount: 2\n")
	writeGitOpsFile(t, filepath.Join(dir, "skills", "z.yaml"), "id: z\ntriggers: [z]\nrequired_evidence:\n  - id: z\n    any_of: [z]\n")
	writeGitOpsFile(t, filepath.Join(dir, "skills", "a.yaml"), "id: a\ntriggers: [a]\nrequired_evidence:\n  - id: a\n    any_of: [a]\n")
	if err := RenderGitOps(gitOpsTestOptions(dir), nil); err != nil {
		t.Fatal(err)
	}
	values := generatedApplicationValues(t, dir)
	project := values["project"].(map[string]any)
	if project["config"] != projectYAML || project["systemPrompt"] != prompt {
		t.Fatalf("exact input did not round-trip\nconfig=%q\nprompt=%q", project["config"], project["systemPrompt"])
	}
	skills := project["skills"].(map[string]any)
	keys := make([]string, 0, len(skills))
	for key := range skills {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	if !reflect.DeepEqual(keys, []string{"a.yaml", "z.yaml"}) || values["replicaCount"] != 2 {
		t.Fatalf("generated values = %#v", values)
	}
}

func TestGitOpsDeterministicAndCheckoutIndependent(t *testing.T) {
	dirA := writeGitOpsConsumer(t, "mode: cron\n", "", nil)
	dirB := writeGitOpsConsumer(t, "mode: cron\n", "", nil)
	if err := RenderGitOps(gitOpsTestOptions(dirA), nil); err != nil {
		t.Fatal(err)
	}
	if err := RenderGitOps(gitOpsTestOptions(dirB), nil); err != nil {
		t.Fatal(err)
	}
	filesA, filesB := readGitOpsTree(t, filepath.Join(dirA, "gitops")), readGitOpsTree(t, filepath.Join(dirB, "gitops"))
	if !reflect.DeepEqual(filesA, filesB) {
		t.Fatal("generated output depends on checkout path")
	}
	if err := RenderGitOps(gitOpsTestOptions(dirA), nil); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(filesA, readGitOpsTree(t, filepath.Join(dirA, "gitops"))) {
		t.Fatal("second render changed output")
	}
	for name, data := range filesA {
		lower := bytes.ToLower(data)
		if bytes.Contains(data, []byte(dirA)) || bytes.Contains(lower, []byte("capz")) || bytes.Contains(lower, []byte("azure")) {
			t.Errorf("%s contains local or project-specific text", name)
		}
	}
}

func TestGitOpsRejectsInvalidConsumerInputs(t *testing.T) {
	tests := []struct{ name, values, prompt, version, want string }{
		{"project collision", "project:\n  existingConfigMap: old\n", "", "", "top-level project"},
		{"inline token", "ai:\n  token: super-secret-provider-token\n", "", "", "credential"},
		{"github token", "note: ghp_abcdefghijklmnopqrstuvwxyz123456\n", "", "", "credential-like"},
		{"pem", "note: |\n  -----BEGIN PRIVATE KEY-----\n  abc\n", "", "", "credential-like"},
		{"url userinfo", "endpoint: https://user:password@example.test/v1\n", "", "", "URL userinfo"},
		{"mutable image", "image:\n  repository: example/image:latest\n", "", "", "mutable image"},
		{"mutable image main", "image:\n  tag: main\n", "", "", "mutable image"},
		{"mutable global image", "global:\n  imageTag: latest\n", "", "", "mutable image"},
		{"mutable image canary", "image:\n  tag: canary\n", "", "", "mutable image"},
		{"openai token", "note: sk-proj-abcdefghijklmnopqrstuvwxyz123456\n", "", "", "credential-like"},
		{"local home path", "note: /Users/alice/private/config\n", "", "", "local workstation"},
		{"credential query", "endpoint: https://example.test/v1?token=abcdefghijklmnop\n", "", "", "credential-bearing URL query"},
		{"duplicate values", "mode: cron\nmode: watch\n", "", "", "duplicate key mode"},
		{"multiple documents", "mode: cron\n---\nmode: watch\n", "", "", "multiple YAML documents"},
		{"mutable version", "mode: cron\n", "", "latest", "semantic version"},
		{"snapshot version", "mode: cron\n", "", "0.9.0-SNAPSHOT", "semantic version"},
		{"build metadata version", "mode: cron\n", "", "1.2.3+build.7", "OCI tag"},
		{"prompt credential", "mode: cron\n", "AI_TOKEN=super-secret-provider-token\n", "", "credential-like"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := writeGitOpsConsumer(t, tt.values, "", nil)
			if tt.prompt != "" {
				writeGitOpsFile(t, filepath.Join(dir, "prompts", "system.md"), tt.prompt)
			}
			opts := gitOpsTestOptions(dir)
			if tt.version != "" {
				opts.ChartVersion = tt.version
			}
			err := RenderGitOps(opts, nil)
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("error = %v, want %q", err, tt.want)
			}
		})
	}
}

func TestGitOpsRejectsLocalFilesystemProject(t *testing.T) {
	dir := writeGitOpsConsumer(t, "mode: cron\n", "", nil)
	writeGitOpsFile(t, filepath.Join(dir, "project.yaml"), minimalProject)
	if err := RenderGitOps(gitOpsTestOptions(dir), nil); err == nil || !strings.Contains(err.Error(), "local filesystem storage") {
		t.Fatalf("error = %v, want local storage rejection", err)
	}
}

func TestGitOpsRejectsInvalidCoordinates(t *testing.T) {
	dir := writeGitOpsConsumer(t, "mode: cron\n", "", nil)
	tests := []struct {
		name, want string
		mutate     func(*GitOpsOptions)
	}{
		{name: "dotted namespace", want: "namespace", mutate: func(opts *GitOpsOptions) { opts.Namespace = "foo.bar" }},
		{name: "long release", want: "53 characters", mutate: func(opts *GitOpsOptions) { opts.Release = strings.Repeat("a", 54) }},
		{name: "embedded chart tag", want: "embedded tag", mutate: func(opts *GitOpsOptions) { opts.Chart = "oci://registry.example.test/charts/aster:0.8.0" }},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			opts := gitOpsTestOptions(dir)
			tt.mutate(&opts)
			if err := RenderGitOps(opts, nil); err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("error = %v, want %q", err, tt.want)
			}
		})
	}
}

func TestGitOpsReleaseNameBoundaries(t *testing.T) {
	t.Run("application only accepts Helm maximum", func(t *testing.T) {
		dir := writeGitOpsConsumer(t, "mode: cron\n", "", nil)
		opts := gitOpsTestOptions(dir)
		opts.Release = strings.Repeat("a", 53)
		if err := RenderGitOps(opts, nil); err != nil {
			t.Fatal(err)
		}
	})
	for length, wantError := range map[int]bool{44: false, 45: true} {
		t.Run(fmt.Sprintf("Fix length %d", length), func(t *testing.T) {
			app := gitOpsFixAppValues("execution", "kata", "workload")
			release := strings.Repeat("a", length)
			platform := fmt.Sprintf("application:\n  releaseName: %s\nexecution:\n  namespace: execution\n  runtimeClassName: kata\n  workloadServiceAccountName: workload\n", release)
			dir := writeGitOpsConsumer(t, app, platform, nil)
			opts := gitOpsTestOptions(dir)
			opts.Release, opts.ExecutionNamespace = release, "execution"
			err := RenderGitOps(opts, nil)
			if wantError && (err == nil || !strings.Contains(err.Error(), "44 characters")) {
				t.Fatalf("error = %v, want platform release length rejection", err)
			}
			if !wantError && err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestGitOpsRejectsPlatformMismatch(t *testing.T) {
	app := gitOpsFixAppValues("execution", "kata", "workload")
	platform := "application:\n  releaseName: wrong\nexecution:\n  namespace: execution\n  runtimeClassName: kata\n  workloadServiceAccountName: workload\n"
	dir := writeGitOpsConsumer(t, app, platform, nil)
	opts := gitOpsTestOptions(dir)
	opts.ExecutionNamespace = "execution"
	if err := RenderGitOps(opts, nil); err == nil || !strings.Contains(err.Error(), "application release") {
		t.Fatalf("error = %v, want release mismatch", err)
	}
}

func TestCheckGitOpsDetectsMissingStaleAndUnexpectedFiles(t *testing.T) {
	tests := []struct {
		name, want string
		mutate     func(*testing.T, string)
	}{
		{"missing", "missing README.md", func(t *testing.T, root string) { os.Remove(filepath.Join(root, "README.md")) }},
		{"stale", "stale README.md", func(t *testing.T, root string) {
			writeGitOpsFile(t, filepath.Join(root, "README.md"), "private prompt content")
		}},
		{"unexpected", "unexpected extra.yaml", func(t *testing.T, root string) {
			writeGitOpsFile(t, filepath.Join(root, "extra.yaml"), "private prompt content")
		}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := writeGitOpsConsumer(t, "mode: cron\n", "", nil)
			opts := gitOpsTestOptions(dir)
			if err := RenderGitOps(opts, nil); err != nil {
				t.Fatal(err)
			}
			tt.mutate(t, filepath.Join(dir, "gitops"))
			var output bytes.Buffer
			err := CheckGitOps(opts, &output)
			if err == nil || !strings.Contains(output.String(), tt.want) || strings.Contains(output.String(), "private prompt content") {
				t.Fatalf("error = %v output = %q", err, output.String())
			}
		})
	}
}

func TestRenderGitOpsDryRunAndPathSafety(t *testing.T) {
	dir := writeGitOpsConsumer(t, "mode: cron\n", "", nil)
	opts := gitOpsTestOptions(dir)
	opts.DryRun = true
	var output bytes.Buffer
	if err := RenderGitOps(opts, &output); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "gitops")); !os.IsNotExist(err) || !strings.Contains(output.String(), "render plan") || !strings.Contains(output.String(), "create README.md") {
		t.Fatalf("dry-run wrote output or omitted plan: %v %q", err, output.String())
	}
	opts = gitOpsTestOptions(dir)
	opts.OutputDir = "../outside"
	if err := RenderGitOps(opts, nil); err == nil || !strings.Contains(err.Error(), "inside the consumer repository") {
		t.Fatalf("traversal error = %v", err)
	}
	outside := t.TempDir()
	writeGitOpsFile(t, filepath.Join(outside, "values.yaml"), "mode: cron\n")
	if err := os.Symlink(filepath.Join(outside, "values.yaml"), filepath.Join(dir, "linked-values.yaml")); err != nil {
		t.Fatal(err)
	}
	opts = gitOpsTestOptions(dir)
	opts.ValuesFile = "linked-values.yaml"
	if err := RenderGitOps(opts, nil); err == nil || !strings.Contains(err.Error(), "symlink") {
		t.Fatalf("symlink error = %v", err)
	}
}

func TestRenderGitOpsRemovesOnlyKnownObsoletePlatformFiles(t *testing.T) {
	app := gitOpsFixAppValues("execution", "kata", "workload")
	platform := "application:\n  releaseName: sample\nexecution:\n  namespace: execution\n  runtimeClassName: kata\n  workloadServiceAccountName: workload\n"
	dir := writeGitOpsConsumer(t, app, platform, nil)
	opts := gitOpsTestOptions(dir)
	opts.ExecutionNamespace = "execution"
	if err := RenderGitOps(opts, nil); err != nil {
		t.Fatal(err)
	}
	writeGitOpsFile(t, filepath.Join(dir, "gitops", "notes.txt"), "leave me")
	writeGitOpsFile(t, filepath.Join(dir, "deploy", "values.yaml"), "mode: cron\n")
	opts.ExecutionNamespace = ""
	if err := RenderGitOps(opts, nil); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "gitops", "platform", "helmrelease.yaml")); !os.IsNotExist(err) {
		t.Fatalf("obsolete platform file remains: %v", err)
	}
	if data, err := os.ReadFile(filepath.Join(dir, "gitops", "notes.txt")); err != nil || string(data) != "leave me" {
		t.Fatalf("unrelated file changed: %q, %v", data, err)
	}
}

func TestRenderGitOpsRejectsObsoleteSymlinkEscape(t *testing.T) {
	dir := writeGitOpsConsumer(t, "mode: cron\n", "", nil)
	root := filepath.Join(dir, "gitops")
	outside := t.TempDir()
	writeGitOpsFile(t, filepath.Join(outside, "helmrelease.yaml"), "outside")
	if err := os.MkdirAll(root, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(root, "platform")); err != nil {
		t.Fatal(err)
	}
	err := RenderGitOps(gitOpsTestOptions(dir), nil)
	if err == nil || !strings.Contains(err.Error(), "non-directory") {
		t.Fatalf("error = %v, want symlink-parent rejection", err)
	}
	if data, readErr := os.ReadFile(filepath.Join(outside, "helmrelease.yaml")); readErr != nil || string(data) != "outside" {
		t.Fatalf("outside file changed: %q, %v", data, readErr)
	}
}

func TestCheckGitOpsRejectsSpecialGeneratedFile(t *testing.T) {
	dir := writeGitOpsConsumer(t, "mode: cron\n", "", nil)
	opts := gitOpsTestOptions(dir)
	if err := RenderGitOps(opts, nil); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, "gitops", "README.md")
	if err := os.Remove(path); err != nil {
		t.Fatal(err)
	}
	if err := syscall.Mkfifo(path, 0o600); err != nil {
		t.Skipf("mkfifo unavailable: %v", err)
	}
	if err := CheckGitOps(opts, nil); err == nil || !strings.Contains(err.Error(), "not a regular file") {
		t.Fatalf("error = %v, want regular-file rejection", err)
	}
}

const gitOpsProject = `id: test
name: Test
testgrid:
  dashboard: test
storage:
  provider: gcs
  bucket: example-bucket
branding:
  title: Test
  base_path: /
  site_url: https://example.test
  source_repo:
    owner: example
    name: example
`

func gitOpsFixAppValues(namespace, runtimeClass, serviceAccount string) string {
	return fmt.Sprintf(`agentSandbox:
  fixRuntime:
    enabled: true
    namespace: %s
    runtimeClassName: %s
    image:
      repository: registry.example.test/aster/fixer
      digest: sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    workloadServiceAccount:
      name: %s
    modelProvider:
      credentialMode: direct
      api: chat_completions
      endpoint: https://provider.example.test/chat/completions
      model: fixture-model
      auth:
        type: none
`, namespace, runtimeClass, serviceAccount)
}

func writeGitOpsConsumer(t *testing.T, appValues, platformValues string, skills map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	writeGitOpsFile(t, filepath.Join(dir, "project.yaml"), gitOpsProject)
	writeGitOpsFile(t, filepath.Join(dir, "prompts", "system.md"), "diagnose from evidence\n")
	writeGitOpsFile(t, filepath.Join(dir, "deploy", "values.yaml"), appValues)
	if platformValues != "" {
		writeGitOpsFile(t, filepath.Join(dir, "deploy", "platform-values.yaml"), platformValues)
	}
	for name, content := range skills {
		writeGitOpsFile(t, filepath.Join(dir, "skills", name), content)
	}
	return dir
}

func gitOpsTestOptions(dir string) GitOpsOptions {
	return GitOpsOptions{ProjectDir: dir, Release: "sample", Namespace: "aster", ChartVersion: "0.9.0", Chart: "oci://registry.example.test/charts/aster", PlatformChart: "oci://registry.example.test/charts/aster-platform", OutputDir: "gitops"}
}

func writeGitOpsFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readGitOpsYAML(t *testing.T, path string) map[string]any {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var object map[string]any
	if err := yaml.Unmarshal(data, &object); err != nil {
		t.Fatal(err)
	}
	return object
}

func generatedApplicationValues(t *testing.T, dir string) map[string]any {
	t.Helper()
	object := readGitOpsYAML(t, filepath.Join(dir, "gitops", "application", "values-configmap.yaml"))
	data := object["data"].(map[string]any)[gitOpsValuesKey].(string)
	var values map[string]any
	if err := yaml.Unmarshal([]byte(data), &values); err != nil {
		t.Fatal(err)
	}
	return values
}

func readGitOpsTree(t *testing.T, root string) map[string][]byte {
	t.Helper()
	out := map[string][]byte{}
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		out[filepath.ToSlash(rel)] = data
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return out
}
