{{- include "aster.validateFixRuntime" . -}}
{{- include "aster.validateAnalysisRuntime" . -}}
{{- $analysis := eq .Values.analysisRuntime.type "orka-container" -}}
{{- if and (or .Values.orka.fixRuntime.enabled $analysis) .Values.orka.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aster.orkaServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aster.labels" . | nindent 4 }}
    app.kubernetes.io/component: orka-runtime
{{- end }}
