package onboard

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/willie-yao/aster/backend/internal/models"
	"github.com/willie-yao/aster/backend/internal/project"
	"github.com/willie-yao/aster/backend/internal/prow/jobconfig"
	"github.com/willie-yao/aster/backend/internal/prowbuild"
	"github.com/willie-yao/aster/backend/internal/storage"
	utilvalidation "k8s.io/apimachinery/pkg/util/validation"
)

// k8sCILogsBucket is the default artifact bucket for Kubernetes TestGrid jobs.
const k8sCILogsBucket = "kubernetes-ci-logs"

// Deploy modes the scaffold targets.
const (
	modePages = "pages"
	modeK8s   = "k8s"
)

func scaffoldGuide(mode string) string {
	if mode == modeK8s {
		return "deploy/README.md"
	}
	return "CHECKLIST.md"
}

// scaffoldPRBody is the PR description: a short summary plus the human steps.
func scaffoldPRBody(name, mode string, aiEnabled bool) string {
	guide := "`" + scaffoldGuide(mode) + "`"
	finalStep := "Complete the GitHub configuration in `CHECKLIST.md` and enable Pages."
	if aiEnabled {
		finalStep = "Complete the GitHub configuration in `CHECKLIST.md` (enable Pages, set the AI provider variables and token)."
	}
	if mode == modeK8s {
		finalStep = "Fill in `deploy/values.yaml`, then follow `deploy/README.md` to install the dashboard with Helm."
	}
	return fmt.Sprintf("Generated by `aster onboard` for **%s**. The job sweep confirmed discovery finds jobs.\n\n"+
		"**Before merging or deploying:**\n"+
		"- Review and fill in `prompts/system.md`.\n"+
		"- Review or trim the inferred `categories` in `project.yaml`.\n"+
		"- %s\n\n"+
		"See %s for the full steps.", name, finalStep, guide)
}

const (
	// DefaultPromptDraftTimeout bounds one prompt-authoring attempt.
	DefaultPromptDraftTimeout = 15 * time.Minute
	defaultPromptDraftTimeout = DefaultPromptDraftTimeout
	minPromptDraftTimeout     = time.Minute
	maxPromptDraftTimeout     = 2 * time.Hour
)

func effectivePromptDraftTimeout(opts Options) time.Duration {
	if opts.PromptTimeout <= 0 {
		return defaultPromptDraftTimeout
	}
	return opts.PromptTimeout
}

func validatePromptMode(mode string) error {
	switch mode {
	case "", promptModeHandoff, promptModeTemplate:
		return nil
	default:
		return fmt.Errorf("--prompt-mode must be handoff or todo-template")
	}
}

func validateOptions(opts *Options) error {
	opts.PromptMode = strings.TrimSpace(opts.PromptMode)
	if err := validatePromptMode(opts.PromptMode); err != nil {
		return err
	}
	if err := validateCredentialSeparation(*opts); err != nil {
		return err
	}
	if err := project.ValidateAIAPI(opts.AIAPI); err != nil {
		return err
	}
	if err := project.ValidateAIAPI(opts.DeploymentAIAPI); err != nil {
		return fmt.Errorf("deployed %w", err)
	}
	if err := validateAIEndpoint(opts.AIEndpoint); err != nil {
		return err
	}
	if err := validateAIEndpoint(opts.DeploymentAIEndpoint); err != nil {
		return fmt.Errorf("deployed %w", err)
	}
	opts.AIAPI = strings.ToLower(strings.TrimSpace(opts.AIAPI))
	if opts.AIAPI == "" {
		opts.AIAPI = project.AIAPIChatCompletions
	}
	opts.DeploymentAIAPI = strings.ToLower(strings.TrimSpace(opts.DeploymentAIAPI))
	if opts.PromptTimeout == 0 {
		opts.PromptTimeout = defaultPromptDraftTimeout
	}
	if opts.PromptTimeout < minPromptDraftTimeout || opts.PromptTimeout > maxPromptDraftTimeout {
		return fmt.Errorf("--prompt-timeout must be between %s and %s", minPromptDraftTimeout, maxPromptDraftTimeout)
	}
	if opts.PlanOut != "" && !opts.DryRun {
		return fmt.Errorf("--plan-out requires --dry-run")
	}
	if opts.PlanOut != "" && opts.OpenPR {
		return fmt.Errorf("--plan-out cannot be combined with --open-pr")
	}
	if (opts.TestGrid == "") == (opts.Bucket == "") {
		return fmt.Errorf("provide exactly one of --testgrid or --bucket")
	}
	if len(opts.ExactJobs) > 0 && opts.Bucket == "" {
		return fmt.Errorf("--exact-job requires --bucket")
	}
	seenExactJobs := map[string]bool{}
	for i, name := range opts.ExactJobs {
		if strings.TrimSpace(name) != name || !project.ValidExactJobName(name) {
			return fmt.Errorf("--exact-job value %d %q is not a safe Prow job name", i+1, name)
		}
		if seenExactJobs[name] {
			return fmt.Errorf("--exact-job value %d duplicates %q", i+1, name)
		}
		seenExactJobs[name] = true
	}
	sort.Strings(opts.ExactJobs)
	if _, _, err := parseRepo(opts.DashboardRepo); err != nil {
		return fmt.Errorf("--dashboard-repo %w", err)
	}
	sourceRepo, err := NormalizeGitHubRepo(opts.SourceRepo)
	if err != nil {
		return fmt.Errorf("--source-repo %w", err)
	}
	opts.SourceRepo = sourceRepo.FullName
	if opts.GCSWebBase != "" && opts.Bucket == "" {
		return fmt.Errorf("--gcsweb-base only applies with --bucket")
	}
	if opts.OpenPR && opts.UpdateExisting {
		return fmt.Errorf("--update-existing applies only to local output and cannot be combined with --open-pr")
	}
	if opts.ReplaceConsumerOwned && !opts.UpdateExisting {
		return fmt.Errorf("--replace-consumer-owned requires --update-existing")
	}
	if opts.ReplaceConsumerOwned && opts.OpenPR {
		return fmt.Errorf("--replace-consumer-owned applies only to reviewed local updates")
	}
	if opts.EngineRef == "" {
		opts.EngineRef = "main"
	}
	switch opts.Mode {
	case "":
		opts.Mode = modePages
	case modePages, modeK8s:
	default:
		return fmt.Errorf("--mode must be %q or %q, got %q", modePages, modeK8s, opts.Mode)
	}
	opts.K8sStorageClass = strings.TrimSpace(opts.K8sStorageClass)
	opts.K8sExistingClaim = strings.TrimSpace(opts.K8sExistingClaim)
	if opts.K8sStorageClass != "" && opts.K8sExistingClaim != "" {
		return fmt.Errorf("--k8s-storage-class and --k8s-existing-claim are mutually exclusive")
	}
	if opts.Mode != modeK8s && (opts.K8sStorageClass != "" || opts.K8sExistingClaim != "") {
		return fmt.Errorf("--k8s-storage-class and --k8s-existing-claim apply only with --mode k8s")
	}
	if opts.Mode == modeK8s && !opts.allowK8sStoragePlaceholder && opts.K8sStorageClass == "" && opts.K8sExistingClaim == "" {
		return fmt.Errorf("--mode k8s requires --k8s-storage-class or --k8s-existing-claim outside the interactive wizard")
	}
	for flagName, value := range map[string]string{
		"--k8s-storage-class":  opts.K8sStorageClass,
		"--k8s-existing-claim": opts.K8sExistingClaim,
	} {
		if value == "" {
			continue
		}
		if errors := utilvalidation.IsDNS1123Subdomain(value); len(errors) > 0 {
			return fmt.Errorf("%s %q is invalid: %s", flagName, value, strings.Join(errors, "; "))
		}
	}
	opts.ArtifactAccess = effectiveArtifactAccess(*opts)
	switch opts.ArtifactAccess {
	case artifactAccessPublic, artifactAccessAuthenticated, artifactAccessPrivate, artifactAccessUnknown:
	default:
		return fmt.Errorf("--artifact-access must be public, authenticated, private, or unknown")
	}
	for i, reason := range opts.ModeReasons {
		reason = strings.TrimSpace(reason)
		if reason == "" {
			return fmt.Errorf("--deployment-reason value %d is empty", i+1)
		}
		opts.ModeReasons[i] = reason
	}
	if opts.OutDir == "" {
		_, name, _ := parseRepo(opts.DashboardRepo)
		opts.OutDir = name
	}
	opts.OutDir = filepath.Clean(opts.OutDir)
	if opts.PlanOut != "" {
		opts.PlanOut = filepath.Clean(opts.PlanOut)
	}
	return nil
}

func validateCredentialSeparation(opts Options) error {
	values := []string{
		opts.TestGrid, opts.Bucket, opts.GCSWebBase, opts.DashboardRepo, opts.SourceRepo,
		opts.ID, opts.Name, opts.ShortName, opts.EngineRef, opts.OutDir, opts.PlanOut, opts.ArtifactAccess,
		opts.K8sStorageClass, opts.K8sExistingClaim, strings.Join(opts.ModeReasons, ","),
		opts.AIAPI, opts.AIEndpoint, opts.AIModel,
		opts.DeploymentAIAPI, opts.DeploymentAIEndpoint, opts.DeploymentAIModel,
	}
	for _, credential := range onboardingCredentialValues(opts) {
		if credential == "" {
			continue
		}
		for _, value := range values {
			if strings.Contains(value, credential) {
				return fmt.Errorf("a credential was supplied in a nonsecret onboarding field; keep tokens in environment variables only")
			}
		}
	}
	return nil
}

func onboardingCredentialValues(opts Options) []string {
	values := []string{opts.AIToken, opts.GitHubToken}
	path := "/var/run/secrets/kubernetes.io/serviceaccount/token"
	if token := readOnboardingCredentialFile(path); token != "" {
		values = append(values, token)
	}
	return values
}

func readOnboardingCredentialFile(path string) string {
	file, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer file.Close()
	raw, err := io.ReadAll(io.LimitReader(file, 64<<10))
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(raw))
}

func validateAIEndpoint(endpoint string) error {
	if strings.TrimSpace(endpoint) == "" {
		return nil
	}
	parsed, err := url.Parse(endpoint)
	if err != nil {
		return fmt.Errorf("AI_ENDPOINT is not a valid URL")
	}
	if (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return fmt.Errorf("AI_ENDPOINT must be an absolute HTTP or HTTPS URL")
	}
	if parsed.User != nil {
		return fmt.Errorf("AI_ENDPOINT must not contain credentials; use AI_TOKEN")
	}
	query, err := url.ParseQuery(parsed.RawQuery)
	if err != nil {
		return fmt.Errorf("AI_ENDPOINT contains an invalid query string")
	}
	for key := range query {
		if credentialQueryKey(key) {
			return fmt.Errorf("AI_ENDPOINT must not contain credential query parameters; use AI_TOKEN")
		}
	}
	return nil
}

func credentialQueryKey(key string) bool {
	lower := strings.ToLower(strings.TrimSpace(key))
	for _, fragment := range []string{"token", "secret", "password", "credential", "api-key", "api_key", "apikey", "access-key", "access_key", "subscription-key", "subscription_key", "signature"} {
		if strings.Contains(lower, fragment) {
			return true
		}
	}
	return lower == "key" || lower == "sig" || strings.HasSuffix(lower, "-key") || strings.HasSuffix(lower, "_key")
}

// sweepConfig builds the minimal in-memory config needed to run discovery.
func sweepConfig(opts Options) *project.Config {
	cfg := &project.Config{
		ID:      derivedID(opts),
		Name:    derivedName(opts),
		Storage: project.Storage{Provider: provider(opts), Bucket: bucket(opts), Base: opts.GCSWebBase},
	}
	if opts.TestGrid != "" {
		cfg.Discovery.TestGridDashboard = opts.TestGrid
	} else {
		cfg.Discovery = project.Discovery{Source: project.DiscoveryBucket, ExactJobs: append([]string(nil), opts.ExactJobs...)}
	}
	return cfg
}

// discover runs the same job discovery the fetcher uses, by source.
func discover(ctx context.Context, cfg *project.Config, includePresubmits bool) (JobSweep, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	if cfg.EffectiveDiscoverySource() == project.DiscoveryBucket {
		backend, err := storage.New(cfg.StorageConfig(), client)
		if err != nil {
			return JobSweep{}, fmt.Errorf("configuring storage: %w", err)
		}
		var jobs []models.ProwJob
		if len(cfg.Discovery.ExactJobs) > 0 {
			jobs, err = prowbuild.DiscoverExactJobs(ctx, backend, includePresubmits, cfg.Discovery.ExactJobs)
		} else {
			jobs, err = prowbuild.DiscoverJobs(ctx, backend, includePresubmits, cfg.Discovery.JobFilters)
		}
		return JobSweep{Jobs: jobs}, err
	}
	jobs, catalog, err := jobconfig.FetchJobConfigsAndCatalog(ctx, client, cfg, "")
	if err != nil {
		return JobSweep{}, err
	}
	if !includePresubmits {
		periodic := jobs[:0]
		for _, job := range jobs {
			if job.JobType == models.JobTypePeriodic {
				periodic = append(periodic, job)
			}
		}
		jobs = periodic
	}
	return JobSweep{Jobs: jobs, CatalogRevision: catalog.Revision}, nil
}

func includePresubmits(opts Options) bool {
	return opts.IncludePresubmits != nil && *opts.IncludePresubmits
}

func deploymentAIAPI(opts Options) string {
	if value := strings.TrimSpace(opts.DeploymentAIAPI); value != "" {
		return value
	}
	return strings.TrimSpace(opts.AIAPI)
}

func deploymentAIEndpoint(opts Options) string {
	if value := strings.TrimSpace(opts.DeploymentAIEndpoint); value != "" {
		return value
	}
	return strings.TrimSpace(opts.AIEndpoint)
}

func deploymentAIModel(opts Options) string {
	if value := strings.TrimSpace(opts.DeploymentAIModel); value != "" {
		return value
	}
	return strings.TrimSpace(opts.AIModel)
}

// buildScaffoldData assembles template input from options and categories.
func buildScaffoldData(opts Options, cats []project.CategoryRule) scaffoldData {
	owner, name := splitRepo(opts.DashboardRepo)
	srcOwner, srcName := splitRepo(opts.SourceRepo)
	mode := opts.Mode
	if mode == "" {
		mode = modePages
	}
	aiEnabled := effectiveAIEnabled(opts)
	aiAPI := deploymentAIAPI(opts)
	if aiAPI == "" || opts.deferDeploymentAI {
		aiAPI = project.AIAPIChatCompletions
	}
	aiEndpoint := deploymentAIEndpoint(opts)
	if aiEndpoint == "" || opts.deferDeploymentAI {
		if aiAPI == project.AIAPIResponses {
			aiEndpoint = "http://<your-model-svc>.<ns>.svc.cluster.local:8000/v1/responses"
		} else {
			aiEndpoint = "http://<your-model-svc>.<ns>.svc.cluster.local:8000/v1/chat/completions"
		}
	}
	aiModel := deploymentAIModel(opts)
	if aiModel == "" || opts.deferDeploymentAI {
		aiModel = "<your-model-id>"
	}
	d := scaffoldData{
		ID:                derivedID(opts),
		Name:              derivedName(opts),
		ShortName:         opts.ShortName,
		Provider:          provider(opts),
		Bucket:            bucket(opts),
		GCSWebBase:        opts.GCSWebBase,
		ExactJobs:         append([]string(nil), opts.ExactJobs...),
		Title:             derivedName(opts) + " Prow Dashboard",
		BasePath:          "/" + name,
		SiteURL:           "https://" + owner + ".github.io/" + name,
		SourceOwner:       srcOwner,
		SourceName:        srcName,
		Categories:        cats,
		IncludePresubmits: includePresubmits(opts),
		EngineRef:         opts.EngineRef,
		Mode:              mode,
		AIEnabled:         aiEnabled,
		AIAPI:             aiAPI,
		AIEndpoint:        aiEndpoint,
		AIModel:           aiModel,
		K8sStorageClass:   opts.K8sStorageClass,
		K8sExistingClaim:  opts.K8sExistingClaim,
		Namespace:         k8sName(derivedID(opts)),
		DashboardName:     name,
	}
	// Kubernetes-native serves at the domain root from the in-cluster server, so
	// there is no gh-pages subpath; site_url is a placeholder until an ingress
	// hostname exists.
	if mode == modeK8s {
		d.BasePath = "/"
		d.SiteURL = "http://localhost:8080"
	}
	if opts.TestGrid != "" {
		d.DiscoveryTestGrid = opts.TestGrid
	} else {
		d.BucketDiscovery = true
	}
	return d
}

func validateGeneratedYAML(yamlText string) error {
	_, err := project.Parse([]byte(yamlText))
	return err
}

func provider(opts Options) string {
	if opts.GCSWebBase != "" {
		return string(storage.ProviderGCSWeb)
	}
	return string(storage.ProviderGCS)
}

func bucket(opts Options) string {
	if opts.Bucket != "" {
		return opts.Bucket
	}
	return k8sCILogsBucket
}

func derivedID(opts Options) string {
	if opts.ID != "" {
		return opts.ID
	}
	_, name := splitRepo(opts.DashboardRepo)
	// Strip a trailing -aster suffix so the id reads like the project.
	id := strings.TrimSuffix(name, "-aster")
	if id == "" {
		id = name
	}
	return id
}

func derivedName(opts Options) string {
	if opts.Name != "" {
		return opts.Name
	}
	return labelFor(derivedID(opts))
}

// k8sName coerces s into a DNS-1123 label safe for a namespace and Helm release
// name: lowercase, non-alphanumerics to '-', collapsed, trimmed, capped at 63.
func k8sName(s string) string {
	var b strings.Builder
	prevDash := false
	for _, r := range strings.ToLower(s) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			prevDash = false
			continue
		}
		if !prevDash {
			b.WriteByte('-')
			prevDash = true
		}
	}
	out := strings.Trim(b.String(), "-")
	if len(out) > 63 {
		out = strings.Trim(out[:63], "-")
	}
	if out == "" {
		out = "dashboard"
	}
	return out
}

func splitRepo(repo string) (owner, name string) {
	owner, name, _ = parseRepo(repo)
	return owner, name
}

// parseRepo strictly parses owner/name with one slash and non-empty parts.
func parseRepo(repo string) (owner, name string, err error) {
	parts := strings.Split(repo, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", fmt.Errorf("must be owner/name, got %q", repo)
	}
	return parts[0], parts[1], nil
}

func render(t *template.Template, data any) (string, error) {
	var b strings.Builder
	if err := t.Execute(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}
