package onboard

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/willie-yao/prow-ai-dashboard/backend/internal/ai"
	"github.com/willie-yao/prow-ai-dashboard/backend/internal/models"
	"github.com/willie-yao/prow-ai-dashboard/backend/internal/project"
	"github.com/willie-yao/prow-ai-dashboard/backend/internal/prow/jobconfig"
	"github.com/willie-yao/prow-ai-dashboard/backend/internal/prowbuild"
	"github.com/willie-yao/prow-ai-dashboard/backend/internal/storage"
)

// k8sCILogsBucket is the default artifact bucket for Kubernetes TestGrid jobs.
const k8sCILogsBucket = "kubernetes-ci-logs"

// Deploy modes the scaffold targets.
const (
	modePages = "pages"
	modeK8s   = "k8s"
)

func scaffoldGuide(mode string) string {
	if mode == modeK8s {
		return "deploy/README.md"
	}
	return "CHECKLIST.md"
}

// scaffoldPRBody is the PR description: a short summary plus the human steps.
func scaffoldPRBody(name, mode string, aiEnabled bool) string {
	guide := "`" + scaffoldGuide(mode) + "`"
	finalStep := "Complete the GitHub configuration in `CHECKLIST.md` and enable Pages."
	if aiEnabled {
		finalStep = "Complete the GitHub configuration in `CHECKLIST.md` (enable Pages, set the AI provider variables and token)."
	}
	if mode == modeK8s {
		finalStep = "Fill in `deploy/values.yaml`, then follow `deploy/README.md` to install the dashboard with Helm."
	}
	return fmt.Sprintf("Generated by `prow-ai-dashboard onboard` for **%s**. The job sweep confirmed discovery finds jobs.\n\n"+
		"**Before merging or deploying:**\n"+
		"- Review and fill in `prompts/system.md`.\n"+
		"- Review or trim the inferred `categories` in `project.yaml`.\n"+
		"- %s\n\n"+
		"See %s for the full steps.", name, finalStep, guide)
}

// buildSystemPrompt drafts prompts/system.md from source docs when AI is
// available. It falls back to the stub on disabled, missing, slow, or failed AI.
func buildSystemPrompt(ctx context.Context, opts Options, data scaffoldData, out io.Writer) (string, bool, error) {
	if opts.NoPrompt || opts.AIToken == "" {
		if opts.AIToken == "" && !opts.NoPrompt {
			fmt.Fprintln(out, "[info] no AI token is set; writing a prompts/system.md stub")
		}
		prompt, err := render(systemPromptTmpl, data)
		return prompt, false, err
	}

	// Bound the whole drafting phase so a hung endpoint degrades to the stub
	// instead of hanging the command.
	ctx, cancel := context.WithTimeout(ctx, promptDraftTimeout)
	defer cancel()

	srcOwner, srcName := splitRepo(opts.SourceRepo)
	httpClient := &http.Client{Timeout: 30 * time.Second}

	fmt.Fprintf(out, "Drafting prompts/system.md from %s/%s documentation...\n", srcOwner, srcName)
	// Empty GitHub token means anonymous public reads.
	docs, err := fetchSourceDocs(ctx, httpClient, srcOwner, srcName, opts.GitHubToken)
	if err != nil {
		fmt.Fprintln(out, "[warn] could not read source repository documentation; writing the stub instead")
		prompt, renderErr := render(systemPromptTmpl, data)
		return prompt, false, renderErr
	}

	client := ai.NewClientWithOptions(ai.Options{
		Token:    opts.AIToken,
		API:      opts.AIAPI,
		Endpoint: opts.AIEndpoint,
		Model:    opts.AIModel,
	})
	body, err := generatePromptBody(ctx, client, data.Name, docs)
	if err != nil {
		fmt.Fprintln(out, "[warn] prompt generation failed; writing the stub instead")
		prompt, renderErr := render(systemPromptTmpl, data)
		return prompt, false, renderErr
	}
	fmt.Fprintf(out, "Drafted prompts/system.md from %d document(s). Review it before deployment.\n", len(docs))
	return composeGeneratedPrompt(data.Name, body), true, nil
}

// promptDraftTimeout bounds doc fetch and one generation call.
const promptDraftTimeout = 3 * time.Minute

func validateOptions(opts *Options) error {
	if err := project.ValidateAIAPI(opts.AIAPI); err != nil {
		return err
	}
	if err := project.ValidateAIAPI(opts.DeploymentAIAPI); err != nil {
		return fmt.Errorf("deployed %w", err)
	}
	if err := validateAIEndpoint(opts.AIEndpoint); err != nil {
		return err
	}
	if err := validateAIEndpoint(opts.DeploymentAIEndpoint); err != nil {
		return fmt.Errorf("deployed %w", err)
	}
	if err := validateCredentialSeparation(*opts); err != nil {
		return err
	}
	opts.AIAPI = strings.ToLower(strings.TrimSpace(opts.AIAPI))
	if opts.AIAPI == "" {
		opts.AIAPI = project.AIAPIChatCompletions
	}
	opts.DeploymentAIAPI = strings.ToLower(strings.TrimSpace(opts.DeploymentAIAPI))
	if (opts.TestGrid == "") == (opts.Bucket == "") {
		return fmt.Errorf("provide exactly one of --testgrid or --bucket")
	}
	if _, _, err := parseRepo(opts.DashboardRepo); err != nil {
		return fmt.Errorf("--dashboard-repo %w", err)
	}
	sourceRepo, err := NormalizeGitHubRepo(opts.SourceRepo)
	if err != nil {
		return fmt.Errorf("--source-repo %w", err)
	}
	opts.SourceRepo = sourceRepo.FullName
	if opts.GCSWebBase != "" && opts.Bucket == "" {
		return fmt.Errorf("--gcsweb-base only applies with --bucket")
	}
	// AI drafting needs an explicit endpoint and model because the engine has no
	// default provider. Without AI, the stub is written.
	if opts.AIToken != "" && !opts.NoPrompt {
		if opts.AIEndpoint == "" || opts.AIModel == "" {
			return fmt.Errorf("AI drafting needs AI_ENDPOINT and AI_MODEL set (your provider's chat-completions URL and model id); set both, or unset AI_TOKEN / pass --no-prompt to write the prompts/system.md stub instead")
		}
	}
	if opts.EngineRef == "" {
		opts.EngineRef = "main"
	}
	switch opts.Mode {
	case "":
		opts.Mode = modePages
	case modePages, modeK8s:
	default:
		return fmt.Errorf("--mode must be %q or %q, got %q", modePages, modeK8s, opts.Mode)
	}
	if opts.OutDir == "" {
		_, name, _ := parseRepo(opts.DashboardRepo)
		opts.OutDir = name
	}
	return nil
}

func validateCredentialSeparation(opts Options) error {
	values := []string{
		opts.TestGrid, opts.Bucket, opts.GCSWebBase, opts.DashboardRepo, opts.SourceRepo,
		opts.ID, opts.Name, opts.ShortName, opts.EngineRef, opts.OutDir,
		opts.AIAPI, opts.AIEndpoint, opts.AIModel,
		opts.DeploymentAIAPI, opts.DeploymentAIEndpoint, opts.DeploymentAIModel,
	}
	for _, credential := range []string{opts.AIToken, opts.GitHubToken} {
		if len(credential) < 8 {
			continue
		}
		for _, value := range values {
			if strings.Contains(value, credential) {
				return fmt.Errorf("a credential was supplied in a nonsecret onboarding field; keep tokens in environment variables only")
			}
		}
	}
	return nil
}

func validateAIEndpoint(endpoint string) error {
	if strings.TrimSpace(endpoint) == "" {
		return nil
	}
	parsed, err := url.Parse(endpoint)
	if err != nil {
		return fmt.Errorf("AI_ENDPOINT is not a valid URL")
	}
	if (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return fmt.Errorf("AI_ENDPOINT must be an absolute HTTP or HTTPS URL")
	}
	if parsed.User != nil {
		return fmt.Errorf("AI_ENDPOINT must not contain credentials; use AI_TOKEN")
	}
	for key := range parsed.Query() {
		switch strings.ToLower(key) {
		case "token", "access_token", "api_key", "apikey", "key", "secret", "password", "signature", "sig":
			return fmt.Errorf("AI_ENDPOINT must not contain credential query parameters; use AI_TOKEN")
		}
	}
	return nil
}

// sweepConfig builds the minimal in-memory config needed to run discovery.
func sweepConfig(opts Options) *project.Config {
	cfg := &project.Config{
		ID:      derivedID(opts),
		Name:    derivedName(opts),
		Storage: project.Storage{Provider: provider(opts), Bucket: bucket(opts), Base: opts.GCSWebBase},
	}
	if opts.TestGrid != "" {
		cfg.TestGrid = project.TestGrid{Dashboard: opts.TestGrid}
	} else {
		cfg.Discovery = project.Discovery{Source: project.DiscoveryBucket}
	}
	return cfg
}

// discover runs the same job discovery the fetcher uses, by source.
func discover(ctx context.Context, cfg *project.Config, includePresubmits bool) ([]models.ProwJob, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	if cfg.EffectiveDiscoverySource() == project.DiscoveryBucket {
		backend, err := storage.New(cfg.StorageConfig(), client)
		if err != nil {
			return nil, fmt.Errorf("configuring storage: %w", err)
		}
		return prowbuild.DiscoverJobs(ctx, backend, includePresubmits, cfg.Discovery.JobFilters)
	}
	jobs, err := jobconfig.FetchJobConfigs(ctx, client, cfg)
	if err != nil {
		return nil, err
	}
	if includePresubmits {
		return jobs, nil
	}
	periodic := jobs[:0]
	for _, j := range jobs {
		if j.JobType == models.JobTypePeriodic {
			periodic = append(periodic, j)
		}
	}
	return periodic, nil
}

func deploymentAIAPI(opts Options) string {
	if value := strings.TrimSpace(opts.DeploymentAIAPI); value != "" {
		return value
	}
	return strings.TrimSpace(opts.AIAPI)
}

func deploymentAIEndpoint(opts Options) string {
	if value := strings.TrimSpace(opts.DeploymentAIEndpoint); value != "" {
		return value
	}
	return strings.TrimSpace(opts.AIEndpoint)
}

func deploymentAIModel(opts Options) string {
	if value := strings.TrimSpace(opts.DeploymentAIModel); value != "" {
		return value
	}
	return strings.TrimSpace(opts.AIModel)
}

// buildScaffoldData assembles template input from options and categories.
func buildScaffoldData(opts Options, cats []project.CategoryRule) scaffoldData {
	owner, name := splitRepo(opts.DashboardRepo)
	srcOwner, srcName := splitRepo(opts.SourceRepo)
	mode := opts.Mode
	if mode == "" {
		mode = modePages
	}
	aiAPI := deploymentAIAPI(opts)
	if aiAPI == "" {
		aiAPI = project.AIAPIChatCompletions
	}
	aiEndpoint := deploymentAIEndpoint(opts)
	if aiEndpoint == "" {
		if aiAPI == project.AIAPIResponses {
			aiEndpoint = "http://<your-model-svc>.<ns>.svc.cluster.local:8000/v1/responses"
		} else {
			aiEndpoint = "http://<your-model-svc>.<ns>.svc.cluster.local:8000/v1/chat/completions"
		}
	}
	aiModel := deploymentAIModel(opts)
	if aiModel == "" {
		aiModel = "<your-model-id>"
	}
	d := scaffoldData{
		ID:                derivedID(opts),
		Name:              derivedName(opts),
		ShortName:         opts.ShortName,
		Provider:          provider(opts),
		Bucket:            bucket(opts),
		GCSWebBase:        opts.GCSWebBase,
		Title:             derivedName(opts) + " Prow Dashboard",
		BasePath:          "/" + name,
		SiteURL:           "https://" + owner + ".github.io/" + name,
		SourceOwner:       srcOwner,
		SourceName:        srcName,
		Categories:        cats,
		IncludePresubmits: opts.IncludePresubmits,
		EngineRef:         opts.EngineRef,
		Mode:              mode,
		AIEnabled:         effectiveAIEnabled(opts),
		AIAPI:             aiAPI,
		AIEndpoint:        aiEndpoint,
		AIModel:           aiModel,
		Namespace:         k8sName(derivedID(opts)),
		DashboardName:     name,
	}
	// Kubernetes-native serves at the domain root from the in-cluster server, so
	// there is no gh-pages subpath; site_url is a placeholder until an ingress
	// hostname exists.
	if mode == modeK8s {
		d.BasePath = "/"
		d.SiteURL = "http://localhost:8080"
	}
	if opts.TestGrid != "" {
		d.DiscoveryTestGrid = opts.TestGrid
	} else {
		d.BucketDiscovery = true
	}
	return d
}

func validateGeneratedYAML(yamlText string) error {
	_, err := project.Parse([]byte(yamlText))
	return err
}

func writeFiles(outDir string, files map[string]string) error {
	if err := validateFileDestination(outDir, files); err != nil {
		return err
	}
	for _, rel := range sortedFilePaths(files) {
		full := filepath.Join(outDir, rel)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(full, []byte(files[rel]), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", rel, err)
		}
	}
	return nil
}

func provider(opts Options) string {
	if opts.GCSWebBase != "" {
		return string(storage.ProviderGCSWeb)
	}
	return string(storage.ProviderGCS)
}

func bucket(opts Options) string {
	if opts.Bucket != "" {
		return opts.Bucket
	}
	return k8sCILogsBucket
}

func derivedID(opts Options) string {
	if opts.ID != "" {
		return opts.ID
	}
	_, name := splitRepo(opts.DashboardRepo)
	// Strip a trailing dashboard suffix so the id reads like the project.
	id := strings.TrimSuffix(name, "-prow-ai-dashboard")
	id = strings.TrimSuffix(id, "-prow-dashboard")
	if id == "" {
		id = name
	}
	return id
}

func derivedName(opts Options) string {
	if opts.Name != "" {
		return opts.Name
	}
	return labelFor(derivedID(opts))
}

// k8sName coerces s into a DNS-1123 label safe for a namespace and Helm release
// name: lowercase, non-alphanumerics to '-', collapsed, trimmed, capped at 63.
func k8sName(s string) string {
	var b strings.Builder
	prevDash := false
	for _, r := range strings.ToLower(s) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			prevDash = false
			continue
		}
		if !prevDash {
			b.WriteByte('-')
			prevDash = true
		}
	}
	out := strings.Trim(b.String(), "-")
	if len(out) > 63 {
		out = strings.Trim(out[:63], "-")
	}
	if out == "" {
		out = "dashboard"
	}
	return out
}

func splitRepo(repo string) (owner, name string) {
	owner, name, _ = parseRepo(repo)
	return owner, name
}

// parseRepo strictly parses owner/name with one slash and non-empty parts.
func parseRepo(repo string) (owner, name string, err error) {
	parts := strings.Split(repo, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", fmt.Errorf("must be owner/name, got %q", repo)
	}
	return parts[0], parts[1], nil
}

func render(t *template.Template, data any) (string, error) {
	var b strings.Builder
	if err := t.Execute(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}
