package onboard

import (
	"net/url"
	"strconv"
	"strings"
	"text/template"

	"github.com/willie-yao/prow-ai-dashboard/backend/internal/project"
)

// scaffoldData is the input to all scaffold templates.
type scaffoldData struct {
	ID                string
	Name              string
	ShortName         string
	DiscoveryTestGrid string // non-empty for testgrid discovery
	BucketDiscovery   bool   // true for bucket discovery
	Provider          string // "gcs" or "gcsweb"
	Bucket            string
	GCSWebBase        string // gcsweb gateway root
	ExactJobs         []string
	Title             string
	BasePath          string
	SiteURL           string
	SourceOwner       string
	SourceName        string
	Categories        []project.CategoryRule
	IncludePresubmits bool
	EngineRef         string
	Mode              string // "pages" or "k8s"
	AIEnabled         bool
	AIAPI             string // seeds deploy/values.yaml ai.api (k8s mode)
	AIEndpoint        string // seeds deploy/values.yaml ai.endpoint (k8s mode)
	AIModel           string // seeds deploy/values.yaml ai.model (k8s mode)
	Namespace         string // k8s namespace / helm release name (k8s mode)
	DashboardName     string // dashboard repo name; the scaffold's directory
}

var yamlTemplateFuncs = template.FuncMap{
	"quote":   strconv.Quote,
	"urlPath": url.PathEscape,
}

var readmeTemplateFuncs = template.FuncMap{
	"shellquote": func(value string) string {
		return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
	},
	"urlPath": url.PathEscape,
}

var projectYAMLTmpl = template.Must(template.New("project.yaml").Funcs(yamlTemplateFuncs).Parse(
	`# Generated by prow-ai-dashboard onboard. Review and edit before deploying.
id: {{quote .ID}}
name: {{quote .Name}}
{{if .ShortName}}short_name: {{quote .ShortName}}
{{end}}{{if .DiscoveryTestGrid}}
# Jobs advertising this testgrid dashboard are discovered automatically.
testgrid:
  dashboard: {{quote .DiscoveryTestGrid}}
{{else}}
# Jobs are discovered by listing the storage bucket's own job indexes.
discovery:
  source: bucket
{{- if .ExactJobs}}
  exact_jobs:
{{- range .ExactJobs}}
    - {{quote .}}
{{- end}}
{{- end}}
{{end}}
# Where this project's Prow build artifacts live.
storage:
  provider: {{.Provider}}
  bucket: {{quote .Bucket}}
{{- if .GCSWebBase}}
  base: {{quote .GCSWebBase}}
{{- end}}
{{if .Categories}}
# Job grouping. First substring match wins; unmatched jobs go in "other".
# Generated from job-name clustering: review, reorder, and relabel as needed.
categories:
{{- range .Categories}}
  - match: {{quote .Match}}
    id: {{quote .ID}}
    label: {{quote .Label}}
{{- end}}
{{end}}
# UI branding.
branding:
  title: {{quote .Title}}
  base_path: {{quote .BasePath}}
  site_url: {{quote .SiteURL}}
  source_repo:
    owner: {{quote .SourceOwner}}
    name: {{quote .SourceName}}

{{if .IncludePresubmits}}
# This project's dashboard includes presubmit jobs.
source:
  include_presubmits: true
{{end}}`))

var deployYAMLTmpl = template.Must(template.New("deploy.yml").Funcs(yamlTemplateFuncs).Parse(
	`name: Deploy Dashboard

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    uses: {{quote (printf "willie-yao/prow-ai-dashboard/.github/workflows/reusable-deploy.yml@%s" .EngineRef)}}
    with:
{{- if not .AIEnabled}}
      ai: false
{{- end}}
      # Repository variables keep provider coordinates out of project.yaml.
      ai-api: ${{"{{"}} vars.AI_API {{"}}"}}
      ai-model: ${{"{{"}} vars.AI_MODEL {{"}}"}}
      ai-endpoint: ${{"{{"}} vars.AI_ENDPOINT {{"}}"}}
      ai-reasoning-effort: ${{"{{"}} vars.AI_REASONING_EFFORT {{"}}"}}
    secrets:
      AI_TOKEN: ${{"{{"}} secrets.AI_TOKEN {{"}}"}}
`))

var k8sValuesTmpl = template.Must(template.New("values.yaml").Funcs(yamlTemplateFuncs).Parse(
	`# Generated by prow-ai-dashboard onboard.
#
# Use values.schema.json from the same published chart version used for install.
# Active values below are settings a new consumer commonly owns. Commented
# values document optional chart features without pinning their current defaults.
#
# The Kubernetes deploy wrapper passes project.yaml, prompts/system.md, and
# skills/* separately with --set-file.
#
# Published values reference:
# helm show values oci://ghcr.io/willie-yao/charts/prow-ai-dashboard \
#   --version <chart-version>

# Empty tag overrides let stable chart upgrades follow the chart appVersion
# instead of retaining an older snapshot through reused values.
global:
  # Empty follows the chart appVersion.
  imageTag: ""

image:
  # Defaults to the engine image repository from the chart.
  # repository: ghcr.io/willie-yao/prow-ai-dashboard
  tag: ""
  # pullPolicy: IfNotPresent

# watch runs a continuously refreshing worker Deployment.
# cron runs a scheduled fetcher CronJob.
# Both modes must keep exactly one writer on the shared volume.
mode: watch

# The volume contains dashboard data and AI cache state. ReadWriteMany is
# required for the writer and server. existingClaim reuses a pre-provisioned
# PVC. retain protects chart-managed data during removal or claim changes.
persistence:
  enabled: true
  existingClaim: ""
  storageClass: "<your-rwx-storage-class>"
  accessMode: ReadWriteMany
  size: 1Gi
  retain: true

ai:
  enabled: {{.AIEnabled}}
  api: {{quote .AIAPI}}
  endpoint: {{quote .AIEndpoint}}
  model: {{quote .AIModel}}
  # Empty uses the provider default. Supported values depend on the provider/model.
  reasoningEffort: ""
  # 0 uses provider metadata or the engine fallback. Set a nonzero value only
  # when the endpoint's documented context window supports it.
  contextWindowTokens: 0
  # The chart never creates external provider credentials. Reference a Secret
  # managed outside this file. When enabling AI later, set this field first.
  existingSecret: {{if .AIEnabled}}"<existing-ai-secret>"{{else}}""{{end}}
  tokenSecretKey: AI_TOKEN

  # Public repositories normally use anonymous source reads. Private source
  # grounding should use a separate read-only GitHub credential Secret.
  githubReadTokenSecretName: ""
  githubReadTokenSecretKey: GITHUB_READ_TOKEN

fetcher:
  # History depth affects dashboard coverage and fetch cost.
  buildsPerJob: 10
  # Concurrent artifact fetches. Increase only after checking storage limits.
  workers: 5
  # Bounds discovery and artifact fetching. Orka Tasks have a separate timeout.
  timeout: 120m

  # Watch-mode cadence. Cron settings below do not schedule a CronJob while
  # mode remains watch.
  watchInterval: 5m
  reconcileInterval: 1h

  # Keep scheduled starts suspended while watch mode is active. Set false only
  # when switching to mode: cron.
  suspend: true

  # Cron-mode settings. Deadlines and retries are separate from model or Orka
  # retries, and apply only when mode is cron.
  # schedule: "0 */6 * * *"
  # concurrencyPolicy: Forbid
  # activeDeadlineSeconds: 36000
  # backoffLimit: -1
  # restartPolicy: ""

  # Optional fetcher environment, resources, and placement:
  # extraEnv: []
  # resources: {}
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}

analysisRuntime:
  # inprocess is the recommended default.
  # orka-container is an experimental opt-in lifecycle sidegrade.
  type: inprocess

  # Enabling these fields does not install Orka. Install and operate a separate
  # Orka release first. The model Secret must exist in the analysis namespace,
  # taskTimeout must exceed the project AI timeout plus startup and result
  # finalization time, and analyzer Tasks must use CPU placement.
  #
  # To use the experimental Orka container runtime, set type to orka-container
  # and uncomment the needed fields inside this existing mapping.
  orkaContainer:
    # namespace: ""
    # api: http://orka.orka-system.svc.cluster.local:8080
    # apiAuth:
    #   existingSecret: ""
    #   tokenKey: token
    # maxConcurrentTasks: 2
    # pollInterval: 2s
    # taskTimeout: 20m
    # retries: 1
    # Empty clears an older image-specific tag during upgrades.
    image:
      # repository: ghcr.io/willie-yao/prow-ai-dashboard/analyzer
      tag: ""
      # pullPolicy: IfNotPresent
    # modelAuth:
    #   existingSecret: "<model-secret-in-analysis-namespace>"
    #   tokenKey: token
    # state:
    #   existingSecret: ""
    #   key: state-key
    # nodeSelector:
    #   agentpool: "<cpu-agentpool>"
    # tolerations: []
    # affinity: {}

# Fix generation is independent of analysisRuntime.type and must also be
# configured in project.yaml. It remains disabled in the generated scaffold.
orka:
  namespace: orka-system

  # Private experimental comparison after authoritative in-process analysis.
  # This does not install Orka or create an Agent. Use a dedicated private PVC
  # and a separate read-only Git credential for private repositories.
  agentAnalysisShadow:
    enabled: false
    # api: http://orka.orka-system.svc.cluster.local:8080
    # agentVersion: v1
    # serviceAccountName: ""
    # maxPerRun: 1
    # admission:
    #   agentRef: "<versioned-orka-agent-name>"
    #   repository:
    #     owner: "<github-owner>"
    #     name: "<github-repository>"
    #   gitSecret: ""
    #   maxTurns: 12
    #   timeout: 10m
    #   retries: 0
    # ledger:
    #   existingClaim: ""
    #   retain: true
    #   accessMode: ReadWriteOnce
    #   size: 1Gi
    #   storageClass: ""

  fixRuntime:
    enabled: false
    # Empty clears an older image-specific tag during upgrades.
    image:
      tag: ""
    # Required before enabling. Match the effective project.yaml fix runtime.
    # admission:
    #   agentRef: "<orka-agent-name>"
    #   repository:
    #     owner: "<github-owner>"
    #     name: "<github-repository>"
    #   maxTurns: 30
    #   allowBash: true
    #   timeout: 10m
    #   retries: 1

  # rbac:
  #   create: true
  #   serviceAccountName: ""

server:
  # Chat is read-only but still authenticated. Enabling chat requires the
  # actions authentication settings and a secure origin.
  chat:
    enabled: false
    # timeout: 2m
    # correctionsEnabled: false

  # Actions enable GitHub writes. admins is a fail-closed allowlist. OAuth and
  # proxy credentials belong in existing Secrets, never in this file. Enabling
  # chat or actions requires secure origin configuration.
  actions:
    enabled: false
    # mode: oauth
    # admins:
    #   - "<github-login>"
    # oauth:
    #   clientId: "<oauth-client-id>"
    #   redirectUrl: "https://dashboard.example.com/api/auth/callback"
    #   # Include OAUTH_CLIENT_SECRET, SESSION_KEY, and BOT_TOKEN when actions are enabled.
    #   existingSecret: "<oauth-secret>"
    # proxy:
    #   header: X-Auth-Request-Email
    #   existingSecret: "<proxy-secret>"

  # ClusterIP behind ingress or an SSO proxy is preferred for authenticated
  # features. Do not expose a public LoadBalancer without origin restrictions.
  service:
    type: ClusterIP
    port: 80
    # loadBalancerSourceRanges: []
    # externalTrafficPolicy: ""
    # internal:
    #   enabled: false
    #   annotations: {}
    # publicOriginAcknowledged: false
    # annotations: {}

  # Optional server resources and placement:
  # resources: {}
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}

ingress:
  enabled: false
  # className: nginx
  # annotations: {}
  # hosts:
  #   - host: dashboard.example.com
  #     paths:
  #       - path: /
  #         pathType: Prefix
  # tls: []

# Enabling NetworkPolicy with an empty ingress list denies all ingress. The
# wizard cannot infer the ingress controller namespace or network topology.
networkPolicy:
  enabled: false
  ingress: []
  # To allow an ingress controller to the server container port, change the
  # ingress value above from [] to a list and add:
  #   - from:
  #       - namespaceSelector:
  #           matchLabels:
  #             kubernetes.io/metadata.name: ingress-nginx
  #     ports:
  #       - protocol: TCP
  #         port: 8080

# The chart also provides non-root pod and container security defaults.
# Override them only after reviewing the complete chart values.
`))

var k8sDeployReadmeTmpl = template.Must(template.New("README.md").Funcs(readmeTemplateFuncs).Parse(
	`# Deploy {{.Name}} with Helm

This is the project contributor path for ` + "`{{.DashboardName}}`" + `. Run commands from
the consumer repository root. The platform administrator prepares the cluster,
platform chart, secure runtime, storage, external identity, and Secret names.

## Consumer files

` + "```text" + `
project.yaml
prompts/system.md
skills/*.yaml
skills/*.yml
deploy/values.yaml
deploy/README.md
` + "```" + `

The ` + "`skills/`" + ` directory is optional unless ` + "`project.yaml`" + ` requires a
consumer skill bundle. Do not add platform manifests, Secret values, a custom
executor Dockerfile, or a private CA to this repository.

## Required platform handoff

Before deployment, obtain these reviewed values from the platform administrator:

- explicit Kubernetes context and application namespace;
- application release name and release-dedicated execution namespace;
- published engine tag and matching application and platform chart versions;
- RWX StorageClass or existing claim;
- existing Secret names and non-secret key names;
- public URL, OAuth callback, and one expected project job name.

The platform administrator guide is:
https://github.com/willie-yao/prow-ai-dashboard/blob/<published-engine-tag>/docs/kubernetes-platform-administrator.md

## Set local variables

` + "```bash" + `
export PROJECT_DIR="$PWD"
export CLI_VERSION="<published-engine-tag>"
export RELEASE="<application-release-from-platform-handoff>"
export NAMESPACE={{shellquote .Namespace}}
export EXECUTION_NAMESPACE="<execution-namespace-from-platform-handoff>"
export PUBLIC_URL="<https-public-dashboard-url>"
export EXPECTED_JOB="<expected-job-name>"
export CONTEXT="<your-kubernetes-context>"
export CHART_VERSION="${CLI_VERSION#v}"
` + "```" + `

Keep the context explicit in every cluster command. Use a published semantic
version and matching chart versions from the same release.

## Download the published CLI

No engine source checkout or local build is required.

` + "```bash" + `
export CLI_DIR="$HOME/.local/share/prow-ai-dashboard/$CLI_VERSION"
case "$(uname -s)-$(uname -m)" in
  Linux-x86_64) CLI_TARGET=linux-amd64 ;;
  Linux-aarch64|Linux-arm64) CLI_TARGET=linux-arm64 ;;
  Darwin-x86_64) CLI_TARGET=darwin-amd64 ;;
  Darwin-arm64) CLI_TARGET=darwin-arm64 ;;
  *) printf 'Unsupported CLI platform\n' >&2; exit 1 ;;
esac
CLI_ASSET="prow-ai-dashboard-fetcher-${CLI_VERSION}-${CLI_TARGET}"
RELEASE_URL="https://github.com/willie-yao/prow-ai-dashboard/releases/download/${CLI_VERSION}"
install -d -m 755 "$CLI_DIR"
if (
  set -euo pipefail
  DOWNLOAD_DIR=$(mktemp -d "${TMPDIR:-/tmp}/prow-cli-download.XXXXXX")
  cleanup_download() {
    find "$DOWNLOAD_DIR" -type f -delete 2>/dev/null || true
    rmdir "$DOWNLOAD_DIR" 2>/dev/null || true
  }
  trap cleanup_download EXIT
  curl --fail --location "$RELEASE_URL/$CLI_ASSET" --output "$DOWNLOAD_DIR/$CLI_ASSET"
  curl --fail --location "$RELEASE_URL/SHA256SUMS" --output "$DOWNLOAD_DIR/SHA256SUMS"
  cd "$DOWNLOAD_DIR"
  CHECKSUM_LINE=$(awk -v asset="$CLI_ASSET" '$2 == asset {print}' SHA256SUMS)
  test -n "$CHECKSUM_LINE"
  if command -v sha256sum >/dev/null && \
    printf '%s\n' "$CHECKSUM_LINE" | sha256sum -c - 2>/dev/null; then
    :
  elif command -v shasum >/dev/null; then
    printf '%s\n' "$CHECKSUM_LINE" | shasum -a 256 --check
  else
    printf 'sha256sum or shasum is required\n' >&2
    exit 1
  fi
  install -m 0755 "$CLI_ASSET" "$CLI_DIR/$CLI_ASSET"
); then
  export FETCHER="$CLI_DIR/$CLI_ASSET"
else
  printf 'CLI download or verification failed\n' >&2
  exit 1
fi
` + "```" + `

## Review deploy/values.yaml

Active values are application-owned settings. Platform prerequisites are not
application values.

1. Review ` + "`project.yaml`" + `, source identity, TestGrid discovery, and categories.
2. Review every claim and TODO in ` + "`prompts/system.md`" + `.
3. Review consumer diagnostic skills.
4. Replace ` + "`<your-rwx-storage-class>`" + ` or set a reviewed existing claim.
{{if .AIEnabled}}5. Confirm provider API, endpoint, model, and replace
   ` + "`<existing-ai-secret>`" + ` in ` + "`ai.existingSecret`" + ` with the exact existing
   name supplied by the platform administrator or Secret manager.
{{else}}5. AI is disabled. No provider Secret is required until it is enabled through
   a reviewed configuration change. When enabling it, set ` + "`ai.existingSecret`" + `
   to the existing name supplied by the platform administrator.
{{end}}6. Keep chat, write actions, public ingress, and experimental runtimes disabled
   until the baseline dashboard is healthy.

Never place tokens, passwords, private keys, or certificate data in consumer
files or Helm arguments.

Inspect the published application values:

` + "```bash" + `
helm show values \
  oci://ghcr.io/willie-yao/charts/prow-ai-dashboard \
  --version "$CHART_VERSION"
` + "```" + `

## Run the static doctor

` + "```bash" + `
"$FETCHER" onboard doctor \
  --project-dir "$PROJECT_DIR"
` + "```" + `

This validates the strict project, prompt, values, credential-reference shape,
and Prow discovery without model-provider or Kubernetes writes.

## Render locally

` + "```bash" + `
"$FETCHER" kubernetes install \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION" \
  --dry-run
` + "```" + `

The render validates chart schema and the current project, prompt, and skills.
It does not contact the cluster or print rendered Secret values.

## Run the live read-only doctor

Run this before any installation:

` + "```bash" + `
"$FETCHER" kubernetes doctor \
  --action install \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION"
` + "```" + `

Fix blocking checks. Review warnings and unverified assumptions with the platform
administrator. Secret checks use metadata only. The doctor does not create a
Sandbox or call the provider.

## Install

` + "```bash" + `
"$FETCHER" kubernetes install \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION"
` + "```" + `

The wrapper refuses an existing release, includes the current project, prompt,
and skills, waits for readiness, and rolls back a failed install.

## Verify

Resolve and wait for the default watch-mode workloads using stable labels:

` + "```bash" + `
SERVER_DEPLOYMENT=$(kubectl --context "$CONTEXT" --namespace "$NAMESPACE" \
  get deployment \
  -l "app.kubernetes.io/instance=$RELEASE,app.kubernetes.io/component=server" \
  -o jsonpath='{.items[0].metadata.name}')
WORKER_DEPLOYMENT=$(kubectl --context "$CONTEXT" --namespace "$NAMESPACE" \
  get deployment \
  -l "app.kubernetes.io/instance=$RELEASE,app.kubernetes.io/component=worker" \
  -o jsonpath='{.items[0].metadata.name}')
SERVER_SERVICE=$(kubectl --context "$CONTEXT" --namespace "$NAMESPACE" \
  get service \
  -l "app.kubernetes.io/instance=$RELEASE,app.kubernetes.io/component=server" \
  -o jsonpath='{.items[0].metadata.name}')

test -n "$SERVER_DEPLOYMENT"
test -n "$WORKER_DEPLOYMENT"
test -n "$SERVER_SERVICE"
kubectl --context "$CONTEXT" --namespace "$NAMESPACE" \
  rollout status "deployment/$SERVER_DEPLOYMENT" --timeout=5m
kubectl --context "$CONTEXT" --namespace "$NAMESPACE" \
  rollout status "deployment/$WORKER_DEPLOYMENT" --timeout=10m
` + "```" + `

Wait for the first fetch and validate local data, public origin, private-file
filtering, and execution cleanup in one fail-closed subshell:

` + "```bash" + `
(
  set -euo pipefail
  VERIFY_DIR=$(mktemp -d "${TMPDIR:-/tmp}/prow-dashboard-verify.XXXXXX")
  PF_PID=""
  cleanup() {
    if [ -n "$PF_PID" ]; then
      kill "$PF_PID" 2>/dev/null || true
      wait "$PF_PID" 2>/dev/null || true
    fi
    find "$VERIFY_DIR" -type f -delete 2>/dev/null || true
    rmdir "$VERIFY_DIR" 2>/dev/null || true
  }
  trap cleanup EXIT

  kubectl --context "$CONTEXT" --namespace "$NAMESPACE" \
    port-forward "service/$SERVER_SERVICE" 18080:80 \
    >"$VERIFY_DIR/port-forward.log" 2>&1 &
  PF_PID=$!
  manifest_ready=false
  for _ in $(seq 1 60); do
    if curl --fail --silent http://127.0.0.1:18080/data/manifest.json \
      --output "$VERIFY_DIR/manifest.json"; then
      manifest_ready=true
      break
    fi
    sleep 10
  done
  if [ "$manifest_ready" != true ]; then
    printf 'manifest did not become available within 10 minutes\n' >&2
    exit 1
  fi

  curl --fail --silent http://127.0.0.1:18080/data/dashboard.json \
    --output "$VERIFY_DIR/dashboard.json"
  python3 -m json.tool "$VERIFY_DIR/manifest.json" >/dev/null
  python3 -m json.tool "$VERIFY_DIR/dashboard.json" >/dev/null
  grep -F "$EXPECTED_JOB" "$VERIFY_DIR/dashboard.json"
  PRIVATE_STATUS=$(curl --silent --output /dev/null --write-out '%{http_code}' \
    http://127.0.0.1:18080/data/ai_cache.json)
  test "$PRIVATE_STATUS" = 404
  curl --fail --silent "${PUBLIC_URL%/}/data/manifest.json" \
    | python3 -m json.tool >/dev/null
  SANDBOXES=$(kubectl --context "$CONTEXT" --namespace "$EXECUTION_NAMESPACE" \
    get sandboxes.agents.x-k8s.io -o name)
  test -z "$SANDBOXES"
)
` + "```" + `

Open the public URL and confirm expected branding, the expected project job, and OAuth sign-in
when authentication is enabled. The private-file check must remain HTTP 404.
Use normal DNS. Do not use a direct-IP kubeconfig, remove the CA, edit
` + "`/etc/hosts`" + `, or set ` + "`insecure-skip-tls-verify`" + `.

## Upgrade

Commit the reviewed consumer state and record rollback inputs before changing
versions:

` + "```bash" + `
test -z "$(git status --porcelain)"
export PRIOR_CONSUMER_COMMIT=$(git rev-parse HEAD)
export PRIOR_FETCHER="$FETCHER"
export PRIOR_CLI_VERSION="$CLI_VERSION"
export PRIOR_CHART_VERSION="$CHART_VERSION"
helm --kube-context "$CONTEXT" --namespace "$NAMESPACE" history "$RELEASE"
export PRIOR_HELM_REVISION=$(helm --kube-context "$CONTEXT" \
  --namespace "$NAMESPACE" status "$RELEASE" --output json \
  | python3 -c 'import json,sys; print(json.load(sys.stdin)["version"])')
` + "```" + `

Download and verify the new published CLI, update ` + "`CHART_VERSION`" + `, then run
the static doctor and live doctor before the guarded upgrade:

` + "```bash" + `
"$FETCHER" onboard doctor --project-dir "$PROJECT_DIR"

"$FETCHER" kubernetes doctor \
  --action upgrade \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION"

"$FETCHER" kubernetes upgrade \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION"
` + "```" + `

## Roll back

If post-upgrade verification fails, roll back to the recorded Helm revision:

` + "```bash" + `
helm --kube-context "$CONTEXT" --namespace "$NAMESPACE" \
  rollback "$RELEASE" "$PRIOR_HELM_REVISION" --wait
` + "```" + `

Restore the prior consumer bundle and matching CLI and chart version before
validating the restored deployment:

` + "```bash" + `
git restore --source="$PRIOR_CONSUMER_COMMIT" -- \
  project.yaml prompts/system.md deploy/values.yaml
git restore --source="$PRIOR_CONSUMER_COMMIT" -- skills 2>/dev/null || true
export FETCHER="$PRIOR_FETCHER"
export CLI_VERSION="$PRIOR_CLI_VERSION"
export CHART_VERSION="$PRIOR_CHART_VERSION"

"$FETCHER" kubernetes doctor \
  --action upgrade \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION"
` + "```" + `

Repeat verification using the restored bundle. Rollback does not delete retained
PVC data or externally owned platform resources.

## References

- Contributor guide:
  https://github.com/willie-yao/prow-ai-dashboard/blob/<published-engine-tag>/docs/kubernetes-contributor-deployment.md
- Platform ownership:
  https://github.com/willie-yao/prow-ai-dashboard/blob/<published-engine-tag>/docs/kubernetes-platform-ownership.md
- Kubernetes operator reference:
  https://github.com/willie-yao/prow-ai-dashboard/blob/<published-engine-tag>/docs/kubernetes-reference.md
- Troubleshooting:
  https://github.com/willie-yao/prow-ai-dashboard/blob/<published-engine-tag>/docs/troubleshooting.md
`))
var systemPromptTmpl = template.Must(template.New("system.md").Parse(
	`# {{.Name}} AI prompt addendum

This file is concatenated between the engine's universal Prow base prompt and
its JSON response schema. It is a source-only baseline and has not been validated
against historical failures. Replace the TODOs with a grounded diagnostic runbook,
then run $author-prow-ai-diagnostics to test and improve it against a representative
historical corpus. Use only project documentation, job configuration, source, and
observed CI artifacts. Leave an item unresolved instead of adding plausible guidance.

The analyzer can read supplied Prow artifacts. If Kubernetes artifact tools are
enabled, they navigate Kubernetes-shaped logs and resource dumps already in the
artifact tree. The analyzer does not connect to a live Kubernetes API and does
not have portal, SSH, arbitrary shell, browser, or local CLI access.

---

You are debugging {{.Name}} CI test failures.

## Architecture

<!-- TODO: describe only component and resource relationships that help localize
failures. -->

## Diagnostic lifecycle

<!-- TODO: describe the relevant provisioning, initialization, reconciliation,
test, and cleanup sequence. Require conditions and timestamped logs to prove the
stalled phase. -->

## Test and job flavors

<!-- TODO: describe test families and environment flavors established by project
documentation or job configuration. Require the analyzer to identify the actual
flavor before applying flavor-specific guidance. -->

## Artifact layout

<!-- TODO: list exact project-specific artifact paths only when documented, and
state what each artifact proves. Label universal Prow files as defaults. -->

## Common failure patterns

<!-- TODO: for each supported pattern, name the signal, required evidence, causal
conclusion to avoid, and remediation boundary. -->

## Transient classification

<!-- TODO: add only project-supported transient rules. Each rule must state the
positive run evidence that permits the classification and the evidence or
persistence that makes the failure non-transient. Do not add generic classes. -->

## Triage order

<!-- TODO: provide an artifact-first sequence from failing test detail, or the
synthesized build-level failure when JUnit is absent, through build-log.txt,
resource conditions, component logs, and a passing comparison. -->

## Relevant source repositories

<!-- TODO: list only grounded GitHub owner/name repositories that can produce
actionable relevant_files paths. -->

## Unresolved details

<!-- TODO: list important artifact paths, flavors, dependency chains, failure
boundaries, or repositories that the available sources do not establish. -->
`))

var checklistTmpl = template.Must(template.New("CHECKLIST.md").Parse(
	`# {{.Name}} dashboard: finish onboarding

This scaffold was generated by ` + "`prow-ai-dashboard onboard`" + `. The job sweep
confirmed your discovery config finds jobs. Remaining steps need a human:

## 1. Review the generated files (required)

- Review the ` + "`prompts/system.md`" + ` source-only baseline. Replace any TODOs and
  confirm its project-specific claims. It has not been validated against historical
  failures. Run ` + "`$author-prow-ai-diagnostics`" + ` after setup to validate and improve it.
- ` + "`project.yaml`" + ` ` + "`categories`" + ` were inferred from job names; reorder,
  rename, or trim them.

## 2. Place the files in the dashboard repo

Dedicated repo: copy these into the repo root (` + "`project_dir: \".\"`" + `).
Existing repo: put them in a subdir and set ` + "`project_dir`" + ` in the workflows.

## 3. GitHub configuration (the agent can't do this for you)

` + "```bash" + `
# Enable Pages with the GitHub Actions build source:
gh api -X POST repos/{{.DashboardOwner}}/{{.DashboardName}}/pages \
  -f build_type=workflow
{{if .AIEnabled}}# Set the deployed provider coordinates and token. The onboarding drafting
# provider is separate and is not configured by these values.
gh variable set AI_API --body {{.AIAPI}} --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_ENDPOINT --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_MODEL --repo {{.DashboardOwner}}/{{.DashboardName}}
# Optional: gh variable set AI_REASONING_EFFORT --body high --repo {{.DashboardOwner}}/{{.DashboardName}}
gh secret set AI_TOKEN --repo {{.DashboardOwner}}/{{.DashboardName}}
{{else}}# AI is disabled in the initial workflow. To enable it later, remove ` + "`ai: false`" + `
# from .github/workflows/deploy.yml, then configure the provider coordinates and token.
gh variable set AI_API --body {{.AIAPI}} --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_ENDPOINT --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_MODEL --repo {{.DashboardOwner}}/{{.DashboardName}}
# Optional: gh variable set AI_REASONING_EFFORT --body high --repo {{.DashboardOwner}}/{{.DashboardName}}
gh secret set AI_TOKEN --repo {{.DashboardOwner}}/{{.DashboardName}}
{{end}}` + "```" + `

## 4. First deploy

Push to ` + "`main`" + ` (or run the **Deploy Dashboard** workflow manually). The
workflows pin the engine at ` + "`@{{.EngineRef}}`" + `; see
https://github.com/willie-yao/prow-ai-dashboard/blob/main/docs/releasing.md
to pin an exact release instead.
`))

// checklistData is the input the checklist template needs.
type checklistData struct {
	Name           string
	DashboardOwner string
	DashboardName  string
	EngineRef      string
	AIEnabled      bool
	AIAPI          string
}

// renderProjectYAML renders and returns the project.yaml text, collapsing the
// blank lines that conditional template blocks leave behind.
func renderProjectYAML(d scaffoldData) (string, error) {
	var b strings.Builder
	if err := projectYAMLTmpl.Execute(&b, d); err != nil {
		return "", err
	}
	return collapseBlankLines(b.String()), nil
}

// collapseBlankLines squeezes runs of blank lines down to one, tidying the
// output left by conditional template sections.
func collapseBlankLines(s string) string {
	lines := strings.Split(s, "\n")
	var out []string
	prevBlank := false
	for _, ln := range lines {
		blank := strings.TrimSpace(ln) == ""
		if blank && prevBlank {
			continue
		}
		out = append(out, ln)
		prevBlank = blank
	}
	return strings.TrimLeft(strings.Join(out, "\n"), "\n")
}
