package onboard

import (
	"net/url"
	"strconv"
	"strings"
	"text/template"

	"github.com/willie-yao/prow-ai-dashboard/backend/internal/project"
)

// scaffoldData is the input to all scaffold templates.
type scaffoldData struct {
	ID                string
	Name              string
	ShortName         string
	DiscoveryTestGrid string // non-empty for testgrid discovery
	BucketDiscovery   bool   // true for bucket discovery
	Provider          string // "gcs" or "gcsweb"
	Bucket            string
	GCSWebBase        string // gcsweb gateway root
	Title             string
	BasePath          string
	SiteURL           string
	SourceOwner       string
	SourceName        string
	Categories        []project.CategoryRule
	IncludePresubmits bool
	EngineRef         string
	Mode              string // "pages" or "k8s"
	AIEnabled         bool
	AIAPI             string // seeds deploy/values.yaml ai.api (k8s mode)
	AIEndpoint        string // seeds deploy/values.yaml ai.endpoint (k8s mode)
	AIModel           string // seeds deploy/values.yaml ai.model (k8s mode)
	Namespace         string // k8s namespace / helm release name (k8s mode)
	DashboardName     string // dashboard repo name; the scaffold's directory
}

var yamlTemplateFuncs = template.FuncMap{
	"quote":   strconv.Quote,
	"urlPath": url.PathEscape,
}

var projectYAMLTmpl = template.Must(template.New("project.yaml").Funcs(yamlTemplateFuncs).Parse(
	`# Generated by prow-ai-dashboard onboard. Review and edit before deploying.
id: {{quote .ID}}
name: {{quote .Name}}
{{if .ShortName}}short_name: {{quote .ShortName}}
{{end}}{{if .DiscoveryTestGrid}}
# Jobs advertising this testgrid dashboard are discovered automatically.
testgrid:
  dashboard: {{quote .DiscoveryTestGrid}}
{{else}}
# Jobs are discovered by listing the storage bucket's own job indexes.
discovery:
  source: bucket
{{- if .IncludePresubmits}}
{{- end}}
{{end}}
# Where this project's Prow build artifacts live.
storage:
  provider: {{.Provider}}
  bucket: {{quote .Bucket}}
{{- if .GCSWebBase}}
  base: {{quote .GCSWebBase}}
{{- end}}
{{if .Categories}}
# Job grouping. First substring match wins; unmatched jobs go in "other".
# Generated from job-name clustering: review, reorder, and relabel as needed.
categories:
{{- range .Categories}}
  - match: {{quote .Match}}
    id: {{quote .ID}}
    label: {{quote .Label}}
{{- end}}
{{end}}
# UI branding.
branding:
  title: {{quote .Title}}
  base_path: {{quote .BasePath}}
  site_url: {{quote .SiteURL}}
  source_repo:
    owner: {{quote .SourceOwner}}
    name: {{quote .SourceName}}

{{if .IncludePresubmits}}
# This project's dashboard includes presubmit jobs.
source:
  include_presubmits: true
{{end}}`))

var deployYAMLTmpl = template.Must(template.New("deploy.yml").Funcs(yamlTemplateFuncs).Parse(
	`name: Deploy Dashboard

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    uses: {{quote (printf "willie-yao/prow-ai-dashboard/.github/workflows/reusable-deploy.yml@%s" .EngineRef)}}
    with:
{{- if not .AIEnabled}}
      ai: false
{{- end}}
      # Repository variables keep provider coordinates out of project.yaml.
      ai-api: ${{"{{"}} vars.AI_API {{"}}"}}
      ai-model: ${{"{{"}} vars.AI_MODEL {{"}}"}}
      ai-endpoint: ${{"{{"}} vars.AI_ENDPOINT {{"}}"}}
    secrets:
      AI_TOKEN: ${{"{{"}} secrets.AI_TOKEN {{"}}"}}
`))

var k8sValuesTmpl = template.Must(template.New("values.yaml").Funcs(yamlTemplateFuncs).Parse(
	`# Generated by prow-ai-dashboard onboard.
#
# Active values below are settings a new consumer commonly owns. Commented
# values document optional chart features without pinning their current defaults.
#
# The Kubernetes deploy wrapper passes project.yaml, prompts/system.md, and
# skills/* separately with --set-file.
#
# Full values reference:
# https://github.com/willie-yao/prow-ai-dashboard/blob/{{urlPath .EngineRef}}/deploy/helm/prow-ai-dashboard/values.yaml
#
# For a published chart version:
# helm show values oci://ghcr.io/willie-yao/charts/prow-ai-dashboard \
#   --version <chart-version>

# Empty tag overrides let stable chart upgrades follow the chart appVersion
# instead of retaining an older snapshot through reused values.
global:
  # Empty follows the chart appVersion.
  imageTag: ""

image:
  # Defaults to the engine image repository from the chart.
  # repository: ghcr.io/willie-yao/prow-ai-dashboard
  tag: ""
  # pullPolicy: IfNotPresent

# watch runs a continuously refreshing worker Deployment.
# cron runs a scheduled fetcher CronJob.
# Both modes must keep exactly one writer on the shared volume.
mode: watch

# The volume contains dashboard data and AI cache state. ReadWriteMany is
# required for the writer and server. existingClaim reuses a pre-provisioned
# PVC. retain protects chart-managed data during removal or claim changes.
persistence:
  enabled: true
  existingClaim: ""
  storageClass: "<your-rwx-storage-class>"
  accessMode: ReadWriteMany
  size: 1Gi
  retain: true

ai:
  enabled: {{.AIEnabled}}
  api: {{quote .AIAPI}}
  endpoint: {{quote .AIEndpoint}}
  model: {{quote .AIModel}}
  # 0 uses provider metadata or the engine fallback. Set a nonzero value only
  # when the endpoint's documented context window supports it.
  contextWindowTokens: 0
  # The chart never creates external provider credentials. Reference a Secret
  # managed outside this file. When enabling AI later, set this field first.
  existingSecret: {{if .AIEnabled}}{{quote (printf "%s-ai" .Namespace)}}{{else}}""{{end}}
  tokenSecretKey: AI_TOKEN

  # Public repositories normally use anonymous source reads. Private source
  # grounding should use a separate read-only GitHub credential Secret.
  githubReadTokenSecretName: ""
  githubReadTokenSecretKey: GITHUB_READ_TOKEN

fetcher:
  # History depth affects dashboard coverage and fetch cost.
  buildsPerJob: 10
  # Concurrent artifact fetches. Increase only after checking storage limits.
  workers: 5
  # Bounds discovery and artifact fetching. Orka Tasks have a separate timeout.
  timeout: 120m

  # Watch-mode cadence. Cron settings below do not schedule a CronJob while
  # mode remains watch.
  watchInterval: 5m
  reconcileInterval: 1h

  # Keep scheduled starts suspended while watch mode is active. Set false only
  # when switching to mode: cron.
  suspend: true

  # Cron-mode settings. Deadlines and retries are separate from model or Orka
  # retries, and apply only when mode is cron.
  # schedule: "0 */6 * * *"
  # concurrencyPolicy: Forbid
  # activeDeadlineSeconds: 36000
  # backoffLimit: -1
  # restartPolicy: ""

  # Optional fetcher environment, resources, and placement:
  # extraEnv: []
  # resources: {}
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}

analysisRuntime:
  # inprocess is the recommended default.
  # orka-container is an experimental opt-in lifecycle sidegrade.
  type: inprocess

  # Enabling these fields does not install Orka. Install and operate a separate
  # Orka release first. The model Secret must exist in the analysis namespace,
  # taskTimeout must exceed the project AI timeout plus startup and result
  # finalization time, and analyzer Tasks must use CPU placement.
  #
  # To use the experimental Orka container runtime, set type to orka-container
  # and uncomment the needed fields inside this existing mapping.
  orkaContainer:
    # namespace: ""
    # api: http://orka.orka-system.svc.cluster.local:8080
    # apiAuth:
    #   existingSecret: ""
    #   tokenKey: token
    # maxConcurrentTasks: 2
    # pollInterval: 2s
    # taskTimeout: 20m
    # retries: 1
    # Empty clears an older image-specific tag during upgrades.
    image:
      # repository: ghcr.io/willie-yao/prow-ai-dashboard/analyzer
      tag: ""
      # pullPolicy: IfNotPresent
    # modelAuth:
    #   existingSecret: "<model-secret-in-analysis-namespace>"
    #   tokenKey: token
    # state:
    #   existingSecret: ""
    #   key: state-key
    # nodeSelector:
    #   agentpool: "<cpu-agentpool>"
    # tolerations: []
    # affinity: {}

# Fix generation is independent of analysisRuntime.type and must also be
# configured in project.yaml. It remains disabled in the generated scaffold.
orka:
  namespace: orka-system

  fixRuntime:
    enabled: false
    # Empty clears an older image-specific tag during upgrades.
    image:
      tag: ""

  # rbac:
  #   create: true
  #   serviceAccountName: ""

server:
  # Chat is read-only but still authenticated. Enabling chat requires the
  # actions authentication settings and a secure origin.
  chat:
    enabled: false
    # timeout: 2m
    # correctionsEnabled: false

  # Actions enable GitHub writes. admins is a fail-closed allowlist. OAuth and
  # proxy credentials belong in existing Secrets, never in this file. Enabling
  # chat or actions requires secure origin configuration.
  actions:
    enabled: false
    # mode: oauth
    # admins:
    #   - "<github-login>"
    # oauth:
    #   clientId: "<oauth-client-id>"
    #   redirectUrl: "https://dashboard.example.com/api/auth/callback"
    #   privateRepositories: false
    #   existingSecret: "<oauth-secret>"
    # proxy:
    #   header: X-Auth-Request-Email
    #   existingSecret: "<proxy-secret>"

  # ClusterIP behind ingress or an SSO proxy is preferred for authenticated
  # features. Do not expose a public LoadBalancer without origin restrictions.
  service:
    type: ClusterIP
    port: 80
    # loadBalancerSourceRanges: []
    # externalTrafficPolicy: ""
    # internal:
    #   enabled: false
    #   annotations: {}
    # publicOriginAcknowledged: false
    # annotations: {}

  # Optional server resources and placement:
  # resources: {}
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}

ingress:
  enabled: false
  # className: nginx
  # annotations: {}
  # hosts:
  #   - host: dashboard.example.com
  #     paths:
  #       - path: /
  #         pathType: Prefix
  # tls: []

# Enabling NetworkPolicy with an empty ingress list denies all ingress. The
# wizard cannot infer the ingress controller namespace or network topology.
networkPolicy:
  enabled: false
  ingress: []
  # To allow an ingress controller to the server container port, change the
  # ingress value above from [] to a list and add:
  #   - from:
  #       - namespaceSelector:
  #           matchLabels:
  #             kubernetes.io/metadata.name: ingress-nginx
  #     ports:
  #       - protocol: TCP
  #         port: 8080

# The chart also provides non-root pod and container security defaults.
# Override them only after reviewing the complete chart values.
`))

var k8sDeployReadmeTmpl = template.Must(template.New("README.md").Funcs(yamlTemplateFuncs).Parse(
	`# Deploying with Helm

This is the Kubernetes-native path. Use it when the model endpoint is private to
the cluster or the dashboard needs authenticated server features.

` + "`project.yaml`" + ` owns portable project behavior and analysis policy.
Helm values own infrastructure, credentials, and execution tuning.

## Consumer bundle

Keep these files together in the consumer repository:

` + "```text" + `
project.yaml
prompts/system.md
skills/*.yaml
skills/*.yml
deploy/values.yaml
deploy/README.md
` + "```" + `

The ` + "`skills/`" + ` directory is optional unless ` + "`project.yaml`" + ` requires a consumer
skill bundle. The deploy wrapper passes the project, prompt, and skill files to
Helm separately with ` + "`--set-file`" + `.

## Understand deploy/values.yaml

Active values are common settings the consumer is expected to own. Commented
values are examples for optional features and do not pin the chart defaults.

- ` + "`mode: watch`" + ` runs one continuously refreshing worker. The active watch
  cadence and ` + "`fetcher.suspend: true`" + ` are safe for this mode.
- ` + "`mode: cron`" + ` runs one scheduled CronJob. When switching, review the
  commented cron settings and set ` + "`fetcher.suspend: false`" + `.
- ` + "`analysisRuntime.type: inprocess`" + ` is the recommended default. The
  ` + "`orka-container`" + ` runtime is experimental and requires a separately installed
  and operated Orka release.
- Chat and actions are disabled. Both require authentication and secure origin
  configuration before exposure.

Print the complete values for the chart version you plan to install:

` + "```bash" + `
helm show values \
  oci://ghcr.io/willie-yao/charts/prow-ai-dashboard \
  --version <chart-version>
` + "```" + `

The source reference used by this scaffold is:
https://github.com/willie-yao/prow-ai-dashboard/blob/{{urlPath .EngineRef}}/deploy/helm/prow-ai-dashboard/values.yaml

## Before installing

1. Review ` + "`project.yaml`" + ` and the inferred categories.
2. Replace the TODOs in ` + "`prompts/system.md`" + `.
3. Set ` + "`persistence.storageClass`" + ` in ` + "`deploy/values.yaml`" + `.
{{if .AIEnabled}}4. Confirm ` + "`ai.endpoint`" + ` and ` + "`ai.model`" + ` in ` + "`deploy/values.yaml`" + `.
5. Create a Kubernetes Secret named ` + "`{{.Namespace}}-ai`" + ` with key ` + "`AI_TOKEN`" + `.
   Use your normal secret manager or a local token file. Never commit the value.
{{else}}4. AI is disabled in the initial scaffold. To enable it later, set ` + "`ai.enabled=true`" + `,
   configure ` + "`ai.api`" + `, ` + "`ai.endpoint`" + `, and ` + "`ai.model`" + `, then reference a
   Kubernetes Secret with ` + "`ai.existingSecret`" + `.
{{end}}
## Validate without cluster writes

From a checkout of ` + "`willie-yao/prow-ai-dashboard`" + `, build the helper and
render the release locally. Replace the chart-version placeholder with a
published release. Live installs and upgrades require Helm 4. The context is
required for the later write but is not contacted by ` + "`--dry-run`" + `.

` + "```bash" + `
make build
./bin/fetcher kubernetes install \
  --project-dir ../{{.DashboardName}} \
  --values deploy/values.yaml \
  --release {{.Namespace}} \
  --namespace {{.Namespace}} \
  --kube-context <context> \
  --chart-version <chart-version> \
  --dry-run
` + "```" + `

## Install

` + "```bash" + `
./bin/fetcher kubernetes install \
  --project-dir ../{{.DashboardName}} \
  --values deploy/values.yaml \
  --release {{.Namespace}} \
  --namespace {{.Namespace}} \
  --kube-context <context> \
  --chart-version <chart-version>
` + "```" + `

## Upgrade

Change ` + "`--chart-version`" + ` for a stable image-only upgrade, or edit other
infrastructure values in ` + "`deploy/values.yaml`" + `, then run:

` + "```bash" + `
./bin/fetcher kubernetes upgrade \
  --project-dir ../{{.DashboardName}} \
  --values deploy/values.yaml \
  --release {{.Namespace}} \
  --namespace {{.Namespace}} \
  --kube-context <context> \
  --chart-version <chart-version>
` + "```" + `

Image-only upgrades do not require editing ` + "`project.yaml`" + `. Live commands
check that install targets a new release and upgrade targets an existing one.
Upgrades start from the new chart defaults, reapply the last user-supplied
values, then apply the current consumer values and bundle. They wait for
readiness and roll back on failure.

## Open the dashboard

` + "```bash" + `
kubectl --context <context> -n {{.Namespace}} port-forward svc/{{.Namespace}}-prow-ai-dashboard-server 8080:80
open http://localhost:8080
` + "```" + `

Follow the first fetch with:

` + "```bash" + `
kubectl --context <context> -n {{.Namespace}} logs -f deploy/{{.Namespace}}-prow-ai-dashboard-worker
` + "```" + `

For manual Helm equivalents, existing ConfigMaps, Orka, authenticated features,
ingress, NetworkPolicy, and production storage, continue with the engine guide:
https://github.com/willie-yao/prow-ai-dashboard/blob/{{urlPath .EngineRef}}/docs/kubernetes.md
`))

var systemPromptTmpl = template.Must(template.New("system.md").Parse(
	`# {{.Name}} AI prompt addendum

This file is concatenated between the engine's universal Prow base prompt and
its JSON response schema. Replace the placeholder below with project-specific
knowledge: the architecture under test, the failure surface, where evidence
lives in the artifacts, and the known transient/flake classes. The richer this
is, the deeper the analysis. See an example at
https://github.com/willie-yao/capz-prow-ai-dashboard/blob/main/prompts/system.md

---

You are debugging {{.Name}} CI test failures.

## Architecture

<!-- TODO: describe the system under test and how its components relate. -->

## Where the evidence lives

<!-- TODO: name the key artifacts (build-log.txt, per-component logs, resource
dumps) and what each is good for. -->

## Known transient / flake classes

<!-- TODO: list infrastructure flakes that should be classified transient (and
NOT turned into a "real bug" verdict), e.g. registry pull timeouts, quota
exhaustion, API server still starting. -->
`))

var checklistTmpl = template.Must(template.New("CHECKLIST.md").Parse(
	`# {{.Name}} dashboard: finish onboarding

This scaffold was generated by ` + "`prow-ai-dashboard onboard`" + `. The job sweep
confirmed your discovery config finds jobs. Remaining steps need a human:

## 1. Review the generated files (required)

- Review the ` + "`prompts/system.md`" + ` draft. Replace any TODOs and confirm its
  project-specific claims. Prompt quality is the biggest lever on analysis depth.
- ` + "`project.yaml`" + ` ` + "`categories`" + ` were inferred from job names; reorder,
  rename, or trim them.

## 2. Place the files in the dashboard repo

Dedicated repo: copy these into the repo root (` + "`project_dir: \".\"`" + `).
Existing repo: put them in a subdir and set ` + "`project_dir`" + ` in the workflows.

## 3. GitHub configuration (the agent can't do this for you)

` + "```bash" + `
# Enable Pages with the GitHub Actions build source:
gh api -X POST repos/{{.DashboardOwner}}/{{.DashboardName}}/pages \
  -f build_type=workflow
{{if .AIEnabled}}# Set the deployed provider coordinates and token. The onboarding drafting
# provider is separate and is not configured by these values.
gh variable set AI_API --body {{.AIAPI}} --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_ENDPOINT --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_MODEL --repo {{.DashboardOwner}}/{{.DashboardName}}
gh secret set AI_TOKEN --repo {{.DashboardOwner}}/{{.DashboardName}}
{{else}}# AI is disabled in the initial workflow. To enable it later, remove ` + "`ai: false`" + `
# from .github/workflows/deploy.yml, then configure the provider coordinates and token.
gh variable set AI_API --body {{.AIAPI}} --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_ENDPOINT --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_MODEL --repo {{.DashboardOwner}}/{{.DashboardName}}
gh secret set AI_TOKEN --repo {{.DashboardOwner}}/{{.DashboardName}}
{{end}}` + "```" + `

## 4. First deploy

Push to ` + "`main`" + ` (or run the **Deploy Dashboard** workflow manually). The
workflows pin the engine at ` + "`@{{.EngineRef}}`" + `; see
https://github.com/willie-yao/prow-ai-dashboard/blob/main/docs/releasing.md
to pin an exact release instead.
`))

// checklistData is the input the checklist template needs.
type checklistData struct {
	Name           string
	DashboardOwner string
	DashboardName  string
	EngineRef      string
	AIEnabled      bool
	AIAPI          string
}

// renderProjectYAML renders and returns the project.yaml text, collapsing the
// blank lines that conditional template blocks leave behind.
func renderProjectYAML(d scaffoldData) (string, error) {
	var b strings.Builder
	if err := projectYAMLTmpl.Execute(&b, d); err != nil {
		return "", err
	}
	return collapseBlankLines(b.String()), nil
}

// collapseBlankLines squeezes runs of blank lines down to one, tidying the
// output left by conditional template sections.
func collapseBlankLines(s string) string {
	lines := strings.Split(s, "\n")
	var out []string
	prevBlank := false
	for _, ln := range lines {
		blank := strings.TrimSpace(ln) == ""
		if blank && prevBlank {
			continue
		}
		out = append(out, ln)
		prevBlank = blank
	}
	return strings.TrimLeft(strings.Join(out, "\n"), "\n")
}
