package onboard

import (
	"net/url"
	"strconv"
	"strings"
	"text/template"

	"github.com/willie-yao/aster/backend/internal/project"
)

// scaffoldData is the input to all scaffold templates.
type scaffoldData struct {
	ID                string
	Name              string
	ShortName         string
	DiscoveryTestGrid string // non-empty for testgrid discovery
	BucketDiscovery   bool   // true for bucket discovery
	Provider          string // "gcs" or "gcsweb"
	Bucket            string
	GCSWebBase        string // gcsweb gateway root
	ExactJobs         []string
	Title             string
	BasePath          string
	SiteURL           string
	SourceOwner       string
	SourceName        string
	Categories        []project.CategoryRule
	IncludePresubmits bool
	EngineRef         string
	Mode              string // "pages" or "k8s"
	AIEnabled         bool
	AIAPI             string // seeds deploy/values.yaml ai.api (k8s mode)
	AIEndpoint        string // seeds deploy/values.yaml ai.endpoint (k8s mode)
	AIModel           string // seeds deploy/values.yaml ai.model (k8s mode)
	K8sStorageClass   string // shared ReadWriteMany storage class (k8s mode)
	K8sExistingClaim  string // existing shared ReadWriteMany PVC (k8s mode)
	Namespace         string // k8s namespace / helm release name (k8s mode)
	DashboardName     string // dashboard repo name; the scaffold's directory
}

var yamlTemplateFuncs = template.FuncMap{
	"quote":   strconv.Quote,
	"urlPath": url.PathEscape,
}

var readmeTemplateFuncs = template.FuncMap{
	"shellquote": func(value string) string {
		return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
	},
	"urlPath": url.PathEscape,
}

var projectYAMLTmpl = template.Must(template.New("project.yaml").Funcs(yamlTemplateFuncs).Parse(
	`# Generated by aster onboard. Review and edit before deploying.
id: {{quote .ID}}
name: {{quote .Name}}
{{if .ShortName}}short_name: {{quote .ShortName}}
{{end}}discovery:
{{- if .DiscoveryTestGrid}}
  # Jobs advertising this TestGrid dashboard are discovered automatically.
  testgrid_dashboard: {{quote .DiscoveryTestGrid}}
{{- else}}
  # Jobs are discovered by listing the storage bucket's own job indexes.
  source: bucket
{{- if .ExactJobs}}
  exact_jobs:
{{- range .ExactJobs}}
    - {{quote .}}
{{- end}}
{{- end}}
{{- end}}
{{- if .IncludePresubmits}}
  # Include presubmit jobs in the dashboard job set.
  include_presubmits: true
{{- end}}
# Where this project's Prow build artifacts live.
storage:
{{- if ne .Provider "gcs"}}
  provider: {{.Provider}}
{{- end}}
  bucket: {{quote .Bucket}}
{{- if .GCSWebBase}}
  base: {{quote .GCSWebBase}}
{{- end}}
{{if .Categories}}
# Job grouping. First substring match wins; unmatched jobs go in "other".
# Generated from job-name clustering: review, reorder, and relabel as needed.
categories:
{{- range .Categories}}
  - match: {{quote .Match}}
    id: {{quote .ID}}
    label: {{quote .Label}}
{{- end}}
{{end}}
# UI branding. The title defaults to "{{.Name}} Prow Dashboard".
branding:
  base_path: {{quote .BasePath}}
  site_url: {{quote .SiteURL}}
  source_repo:
    owner: {{quote .SourceOwner}}
    name: {{quote .SourceName}}

`))

var deployYAMLTmpl = template.Must(template.New("deploy.yml").Funcs(yamlTemplateFuncs).Parse(
	`name: Deploy Dashboard

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    uses: {{quote (printf "willie-yao/aster/.github/workflows/reusable-deploy.yml@%s" .EngineRef)}}
    with:
{{- if not .AIEnabled}}
      ai: false
{{- end}}
      # Repository variables keep provider coordinates out of project.yaml.
      ai-api: ${{"{{"}} vars.AI_API {{"}}"}}
      ai-model: ${{"{{"}} vars.AI_MODEL {{"}}"}}
      ai-endpoint: ${{"{{"}} vars.AI_ENDPOINT {{"}}"}}
      ai-reasoning-effort: ${{"{{"}} vars.AI_REASONING_EFFORT {{"}}"}}
    secrets:
      AI_TOKEN: ${{"{{"}} secrets.AI_TOKEN {{"}}"}}
      # Only used when pull_requests.comment.enabled is set. A reusable workflow
      # receives no secret it is not passed, so these are mapped whether or not
      # commenting is on; unset secrets arrive empty and the feature stays off.
      ASTER_APP_ID: ${{"{{"}} secrets.ASTER_APP_ID {{"}}"}}
      ASTER_APP_PRIVATE_KEY: ${{"{{"}} secrets.ASTER_APP_PRIVATE_KEY {{"}}"}}
`))

var k8sValuesTmpl = template.Must(template.New("values.yaml").Funcs(yamlTemplateFuncs).Parse(
	`# Generated by aster onboard.
#
# This file records consumer-specific decisions. All omitted settings use the
# defaults from the matching published chart version.
#
# The Kubernetes deploy wrapper passes project.yaml, prompts/system.md, and
# skills/* separately with --set-file.
#
# Published values reference:
# helm show values oci://ghcr.io/willie-yao/charts/aster \
#   --version <chart-version>

# The shared volume must support ReadWriteMany. Select either an existing claim
# or the reviewed storage class supplied during onboarding.
persistence:
{{- if .K8sExistingClaim}}
  existingClaim: {{quote .K8sExistingClaim}}
{{- else}}
  storageClass: {{if .K8sStorageClass}}{{quote .K8sStorageClass}}{{else}}"<your-rwx-storage-class>"{{end}}
{{- end}}

# Provider coordinates and credentials are deployment-owned, not project.yaml.
ai:
  enabled: {{.AIEnabled}}
  api: {{quote .AIAPI}}
  endpoint: {{quote .AIEndpoint}}
  model: {{quote .AIModel}}
  existingSecret: {{if .AIEnabled}}"<existing-ai-secret>"{{else}}""{{end}}
  githubReadTokenSecretName: {{if .AIEnabled}}"<existing-github-read-secret>"{{else}}""{{end}}

fetcher:
  # Intentionally longer than the chart default for first-run artifact discovery.
  timeout: 120m
  # Keep CronJob starts disabled while the chart-default watch worker is active.
  suspend: true
`))

var k8sDeployReadmeTmpl = template.Must(template.New("README.md").Funcs(readmeTemplateFuncs).Parse(
	`# Deploy {{.Name}} with Helm

This handoff is for the ` + "`{{.DashboardName}}`" + ` consumer repository. Run
commands from its root. No engine source checkout or local build is required.

Use the published CLI and paired chart version from one release. The canonical
CLI download, platform setup, and detailed operating procedures are linked at
the end of this file.

## Project variables

` + "```bash" + `
export PROJECT_DIR="$PWD"
export ASTER="<verified-aster-path>"
export CLI_VERSION="<published-engine-tag>"
export CHART_VERSION="${CLI_VERSION#v}"
export RELEASE="<application-release-from-platform-handoff>"
export NAMESPACE={{shellquote .Namespace}}
export EXECUTION_NAMESPACE="" # set when Agent Sandbox Fix is enabled
export CONTEXT="<explicit-kubernetes-context>"
export PUBLIC_URL="" # set when an external public origin is configured
export EXPECTED_JOB="<expected-job-name>"
` + "```" + `

Keep the context explicit in every Kubernetes and Helm command. The platform
administrator supplies the release, application namespace, storage, Secret names,
and expected project job. Agent Sandbox and public-origin values are required
only when those features are enabled.

## Review the consumer bundle

Review project.yaml, prompts/system.md, optional skills, and deploy/values.yaml.
Replace storage and Secret-name placeholders. Keep credentials out of files and
Helm arguments.
{{if .AIEnabled}}AI is enabled. Set ai.existingSecret to the reviewed existing provider Secret
name and verify the non-secret key name.
{{else}}AI is disabled. No provider Secret is required. Keep ai.existingSecret as a
placeholder until AI is enabled through a reviewed configuration change.
{{end}}Keep optional chat, write actions, ingress, and experimental Agent Sandbox features disabled
until the baseline dashboard is healthy.

## Static validation and local render

` + "```bash" + `
"$ASTER" onboard doctor --project-dir "$PROJECT_DIR"

"$ASTER" kubernetes install \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION" \
  --dry-run
` + "```" + `

The static doctor and local render do not call the provider or write cluster
resources.

## Live doctor and guarded install

` + "```bash" + `
"$ASTER" kubernetes doctor \
  --action install \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION"

"$ASTER" kubernetes install \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION"
` + "```" + `

Resolve every blocking doctor check before installation. Secret checks use
metadata only. The doctor does not create a Sandbox or call the provider.

## Verify

` + "```bash" + `
SERVER=$(kubectl --context "$CONTEXT" -n "$NAMESPACE" get deployment \
  -l "app.kubernetes.io/instance=$RELEASE,app.kubernetes.io/component=server" \
  -o jsonpath='{.items[0].metadata.name}')
WRITER=$(kubectl --context "$CONTEXT" -n "$NAMESPACE" get deployment \
  -l "app.kubernetes.io/instance=$RELEASE,app.kubernetes.io/component=worker" \
  -o jsonpath='{.items[0].metadata.name}')
SERVICE=$(kubectl --context "$CONTEXT" -n "$NAMESPACE" get service \
  -l "app.kubernetes.io/instance=$RELEASE,app.kubernetes.io/component=server" \
  -o jsonpath='{.items[0].metadata.name}')
test -n "$SERVER" && test -n "$WRITER" && test -n "$SERVICE"
kubectl --context "$CONTEXT" -n "$NAMESPACE" \
  rollout status "deployment/$SERVER" --timeout=5m
kubectl --context "$CONTEXT" -n "$NAMESPACE" \
  rollout status "deployment/$WRITER" --timeout=10m
` + "```" + `

Port-forward the Service in a second terminal:

` + "```bash" + `
kubectl --context "$CONTEXT" -n "$NAMESPACE" \
  port-forward "service/$SERVICE" 18080:80
` + "```" + `

Then verify data, private-file filtering, the public origin, and execution
cleanup:

` + "```bash" + `
curl --fail --retry 60 --retry-delay 10 --retry-connrefused \
  http://127.0.0.1:18080/data/manifest.json | python3 -m json.tool >/dev/null
curl --fail http://127.0.0.1:18080/data/dashboard.json | grep -F "$EXPECTED_JOB"
test "$(curl --silent --output /dev/null --write-out '%{http_code}' \
  http://127.0.0.1:18080/data/ai_cache.json)" = 404
if [ -n "$PUBLIC_URL" ]; then
  curl --fail "${PUBLIC_URL%/}/data/manifest.json" | python3 -m json.tool >/dev/null
fi
if [ -n "$EXECUTION_NAMESPACE" ]; then
  test -z "$(kubectl --context "$CONTEXT" -n "$EXECUTION_NAMESPACE" \
    get sandboxes.agents.x-k8s.io -o name)"
fi
` + "```" + `

Confirm branding, the expected project job, and authentication when enabled.
Use normal DNS and verified TLS. Do not use a direct-IP kubeconfig, edit
/etc/hosts, remove the cluster CA, or disable TLS verification.

## Guarded upgrade

Commit the reviewed consumer state and record the prior Helm revision. Verify
the new CLI and matching chart version before running:

` + "```bash" + `
test -z "$(git status --porcelain)"
export PRIOR_CONSUMER_COMMIT=$(git rev-parse HEAD)
export PRIOR_HELM_REVISION=$(helm --kube-context "$CONTEXT" -n "$NAMESPACE" \
  status "$RELEASE" --output json \
  | python3 -c 'import json,sys; print(json.load(sys.stdin)["version"])')

"$ASTER" onboard doctor --project-dir "$PROJECT_DIR"
"$ASTER" kubernetes doctor \
  --action upgrade \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION"
"$ASTER" kubernetes upgrade \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION"
` + "```" + `

Repeat verification after the upgrade.

## Roll back

` + "```bash" + `
helm --kube-context "$CONTEXT" -n "$NAMESPACE" \
  rollback "$RELEASE" "$PRIOR_HELM_REVISION" --wait
git restore --source="$PRIOR_CONSUMER_COMMIT" -- \
  project.yaml prompts/system.md deploy/values.yaml
git restore --source="$PRIOR_CONSUMER_COMMIT" -- skills 2>/dev/null || true
` + "```" + `

Restore the CLI and chart version matching the prior consumer state, rerun the
live doctor with ` + "`--action upgrade`" + `, and repeat verification. Rollback
does not delete retained PVC data or externally owned platform resources.

## Versioned references

Print URLs pinned to the selected ` + "`CLI_VERSION`" + ` before opening the generic
documentation:

` + "```bash" + `
for path in \
  docs/kubernetes.md \
  docs/kubernetes-platform.md \
  docs/kubernetes-reference.md \
  docs/troubleshooting.md; do
  printf 'https://github.com/willie-yao/aster/blob/%s/%s\n' \
    "$CLI_VERSION" "$path"
done
` + "```" + `
`))
var systemPromptTmpl = template.Must(template.New("system.md").Parse(
	`# {{.Name}} AI prompt addendum

This file is concatenated between the engine's universal Prow base prompt and
its JSON response schema. It is a source-only baseline and has not been validated
against historical failures. Replace the TODOs with a grounded diagnostic runbook,
then run $author-aster-diagnostics to test and improve it against a representative
historical corpus. Use only project documentation, job configuration, source, and
observed CI artifacts. Leave an item unresolved instead of adding plausible guidance.

The analyzer can read supplied Prow artifacts. If Kubernetes artifact tools are
enabled, they navigate Kubernetes-shaped logs and resource dumps already in the
artifact tree. The analyzer does not connect to a live Kubernetes API and does
not have portal, SSH, arbitrary shell, browser, or local CLI access.

---

You are debugging {{.Name}} CI test failures.

## Architecture

<!-- TODO: describe only component and resource relationships that help localize
failures. -->

## Diagnostic lifecycle

<!-- TODO: describe the relevant provisioning, initialization, reconciliation,
test, and cleanup sequence. Require conditions and timestamped logs to prove the
stalled phase. -->

## Test and job flavors

<!-- TODO: describe test families and environment flavors established by project
documentation or job configuration. Require the analyzer to identify the actual
flavor before applying flavor-specific guidance. -->

## Artifact layout

<!-- TODO: list exact project-specific artifact paths only when documented, and
state what each artifact proves. Label universal Prow files as defaults. -->

## Common failure patterns

<!-- TODO: for each supported pattern, name the signal, required evidence, causal
conclusion to avoid, and remediation boundary. -->

## Transient classification

<!-- TODO: add only project-supported transient rules. Each rule must state the
positive run evidence that permits the classification and the evidence or
persistence that makes the failure non-transient. Do not add generic classes. -->

## Triage order

<!-- TODO: provide an artifact-first sequence from failing test detail, or the
synthesized build-level failure when JUnit is absent, through build-log.txt,
resource conditions, component logs, and a passing comparison. -->

## Relevant source repositories

<!-- TODO: list only grounded GitHub owner/name repositories that can produce
actionable relevant_files paths. -->

## Unresolved details

<!-- TODO: list important artifact paths, flavors, dependency chains, failure
boundaries, or repositories that the available sources do not establish. -->
`))

var checklistTmpl = template.Must(template.New("CHECKLIST.md").Parse(
	`# {{.Name}} dashboard: finish onboarding

This scaffold was generated by ` + "`aster onboard`" + `. The job sweep
confirmed your discovery config finds jobs. Remaining steps need a human:

## 1. Review the generated files (required)

- Review the ` + "`prompts/system.md`" + ` source-only baseline. Replace any TODOs and
  confirm its project-specific claims. It has not been validated against historical
  failures. Run ` + "`$author-aster-diagnostics`" + ` after setup to validate and improve it.
- ` + "`project.yaml`" + ` ` + "`categories`" + ` were inferred from job names; reorder,
  rename, or trim them.

## 2. Place the files in the dashboard repo

Dedicated repo: copy these into the repo root (` + "`project_dir: \".\"`" + `).
Existing repo: put them in a subdir and set ` + "`project_dir`" + ` in the workflows.

## 3. GitHub configuration (the agent can't do this for you)

` + "```bash" + `
# Enable Pages with the GitHub Actions build source:
gh api -X POST repos/{{.DashboardOwner}}/{{.DashboardName}}/pages \
  -f build_type=workflow
{{if .AIEnabled}}# Set the deployed provider coordinates and token. The onboarding drafting
# provider is separate and is not configured by these values.
gh variable set AI_API --body {{.AIAPI}} --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_ENDPOINT --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_MODEL --repo {{.DashboardOwner}}/{{.DashboardName}}
# Optional: gh variable set AI_REASONING_EFFORT --body high --repo {{.DashboardOwner}}/{{.DashboardName}}
gh secret set AI_TOKEN --repo {{.DashboardOwner}}/{{.DashboardName}}
{{else}}# AI is disabled in the initial workflow. To enable it later, remove ` + "`ai: false`" + `
# from .github/workflows/deploy.yml, then configure the provider coordinates and token.
gh variable set AI_API --body {{.AIAPI}} --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_ENDPOINT --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_MODEL --repo {{.DashboardOwner}}/{{.DashboardName}}
# Optional: gh variable set AI_REASONING_EFFORT --body high --repo {{.DashboardOwner}}/{{.DashboardName}}
gh secret set AI_TOKEN --repo {{.DashboardOwner}}/{{.DashboardName}}
{{end}}` + "```" + `

## 4. First deploy

Push to ` + "`main`" + ` (or run the **Deploy Dashboard** workflow manually). The
workflows pin the engine at ` + "`@{{.EngineRef}}`" + `; see
https://github.com/willie-yao/aster/blob/main/docs/releasing.md
to pin an exact release instead.
`))

// checklistData is the input the checklist template needs.
type checklistData struct {
	Name           string
	DashboardOwner string
	DashboardName  string
	EngineRef      string
	AIEnabled      bool
	AIAPI          string
}

// renderProjectYAML renders and returns the project.yaml text, collapsing the
// blank lines that conditional template blocks leave behind.
func renderProjectYAML(d scaffoldData) (string, error) {
	var b strings.Builder
	if err := projectYAMLTmpl.Execute(&b, d); err != nil {
		return "", err
	}
	return collapseBlankLines(b.String()), nil
}

// collapseBlankLines squeezes runs of blank lines down to one, tidying the
// output left by conditional template sections.
func collapseBlankLines(s string) string {
	lines := strings.Split(s, "\n")
	var out []string
	prevBlank := false
	for _, ln := range lines {
		blank := strings.TrimSpace(ln) == ""
		if blank && prevBlank {
			continue
		}
		out = append(out, ln)
		prevBlank = blank
	}
	return strings.TrimLeft(strings.Join(out, "\n"), "\n")
}
